### ISSUE TITLE
Finish renaming `snippets` to `translations`

### ISSUE THREAD

**Issue by turnerhayes** [codeforboston/cliff-effects#1019]
#1015 got most of the places but there are still a few stragglers; search for `snip` (case insensitive) to find some.

**Comment by knod** [comment]
There's also a couple files where I shortened it to `sn` because everything was taking up so much space that I just lost it. It might just be '/src/forms/output/Summary.js'.

**Comment by turnerhayes** [comment]
I think I got those in #1015--do you still see them?

**Comment by knod** [comment]
Wow, didn't see that. I think you got 'em all, pokemaster.
