### ISSUE TITLE
Replace Project Hope logo w/ CfB logo

### ISSUE THREAD

**Issue by lianilychee** [codeforboston/cliff-effects#103]
Self-explanatory.

**Comment by lianilychee** [comment]
I know I just merged [PR 112](https://github.com/codeforboston/cliff-effects/pull/112) but I realized the favicon is still the Project Hope logo.

**Comment by knod** [comment]
@lianilychee It actually may just be that you need to right-click on the tab and select 'Reload'.

**Comment by lianilychee** [comment]
That's incredibly awkward.  You're right.  Weird, because this was on an `npm start` too.

I'm going to keep the issue open anyway, till I submit a PR to convert the logo from PNG -> SVG.

**Comment by knod** [comment]
@lianilychee: Ok, we can keep the issue open. I'm going to merge the pull request and change its name so that it doesn't accidentally close this.
