### ISSUE TITLE
MOD:  Left-align all form copy

### ISSUE THREAD

**Issue by lianilychee** [codeforboston/cliff-effects#13]
Desired Outcome:
![image](https://user-images.githubusercontent.com/6895034/30089904-d2228c94-927d-11e7-9201-e69a28e69638.png)

The longest line is center-justified, and everything else is justified to that.

Pages:
* [x] Current Benefits
* [x] Citizenship Status

**Comment by knod** [comment]
Also addressed on the dev branch. Should be visible on the website. Not sure whether to check off the items or not.
