### ISSUE TITLE
Add 'Feedback' link to github issues page

### ISSUE THREAD

**Issue by knod** [codeforboston/cliff-effects#133]
A 'Feedback' button seems like a good idea. I'm not sure if/how we want to handle our issue template to be more flexible so it can be for bugs and suggestions both.

Do we want it in the menu bar after the beta warning? Do we want it elsewhere? Also, do we want a survey after the 'Results' page to ask some guided questions about the user's experience? Maybe that should be in a different issue.

**Comment by lianilychee** [comment]
cc @anhase @zzyyfff 

This is a good suggestion, Michelle, and is something that we need to figure out part-and-parcel with the process of user-testing.

**Comment by lianilychee** [comment]
Summary update on user-testing process:  We will not be giving access to our technical issues board. 
 The way we've plotted it out will allow for face-to-face user-testing with CSP, PH, and PH case workers, and for the testing team to convert feedback into actionable issues.

As written by Andrew on Slack #cliff-effects:
> User testing timeline: In January 2018 we are going to begin user testing. The phases are:
1) Demo / test the MVP to the Center for Social Policy and Project Hope, with a clear road map for development and a package of recommendations around design. 
2) Assuming the demo goes well, Kristin from Project Hope would help us organize user testing with their case managers. We still need to think about what the content of the testing would look like with case managers. Ideally, they would bring anonymized client data. There's also a question of other audiences who might be interested in testing the MVP (other policy makers, funders, government workers?). 
3) Clients test the MVP with case managers. I expect these tests would be one-on-one, as opposed to a focus group. Need to think about what the content of the testing would look like with clients. Based on the feedback from these groups, we will be in a position to assess how to build on CfB's work so far.
