### ISSUE TITLE
Changes needed for tablet use?

### ISSUE THREAD

**Issue by knod** [codeforboston/cliff-effects#134]
This answer is needed fairly urgently. I recall something about clients using tablets to fill out the form. Is that still the case? If so, what browsers will they have access to? If not Chrome, we'll need to really dig into making this compatible with other browsers. Also, do we need the page to be fluid? It could probably be used with a tablet in landscape modes for some sizes of tablets without cutting off part of the page. Not sure about portrait mode.

**Comment by lianilychee** [comment]
cc @anhase - thoughts?

Michelle, that's an excellent thought, thanks for remembering!

I think we should keep to our priority stack, of which rendering SNAP and Section 8 benefit amounts in results pg were first and foremost.

I can run tests with a tablet first, before we decide criticality regarding browser-size reactivity.  re: browser compatibility: my first hunch is that this is out-of-scope, but tell me @knod - how complex do you foresee that being, on the following scale?  1 is easy.  2 is medium.  4 is hard.  8 is "so-complex-we're-gonna-need-multiple-devs"

**Comment by knod** [comment]
Hehe, interesting way of putting it. Without some preliminary research, I'm not comfortable giving any numbers at all. Looking into it should be a 1-2, though.

**Comment by lianilychee** [comment]
![image](https://user-images.githubusercontent.com/6895034/32202302-19482476-bdb2-11e7-8b88-d78f89cd9c3b.png)
 iPad, chrome, landscape orientation.

**Comment by knod** [comment]
@lianilychee Thanks for testing it out!

**Comment by knod** [comment]
Worth another go?

**Comment by ManickYoj** [comment]
@knod I think this was resolved by @wacii on #282 . Can we consider this resolved? It's not perfect, but it's usable, which is a massive step.

**Comment by wacii** [comment]
I'm doing some more work on this.

**Comment by wacii** [comment]
I addressed all the problems I found. There are likely more out there, but only so many I can find using a single device.

**Comment by knod** [comment]
*Now* fixed by merge of #292.
