### ISSUE TITLE
Change 'About' page target, fix broken link interface

### ISSUE THREAD

**Issue by knod** [codeforboston/cliff-effects#136]
From what was expressed at the last two meetings, it occurs to me that we might want the 'About' page to point to our repo's README instead of at any particular organization's page. Also, somewhere along the way (probably when trying to switch from react-redirect), the 'About' page link got broken. Those can be taken care of in one go.

Like the other similar issues - changing the logo, etc. - I'm going to put this on the MVP milestone. Feel free to remove it if desired.

**Comment by lianilychee** [comment]
cc @anhase 

*Background:* Design team suggested pointing to Project Hope's About in September, after actually considering pointing to the repo README.  However, we determined that our README ought to continue being an internal-facing / dev-facing tool resource, true to spirit of a README.

*Suggestion:* I agree we should not point to PH's about, but I also maintain we should not point to our README.  What about this as compromise?  We have a separate about page that:
- includes cliff effects definition from README
- explains that this is a prototype (the disclaimer, but a little more detailed)
- gives background about why this is being created and rough timeline: collaboration between CfB, PH, Center for <?>, started in Nov 2016

What do you two think?

**Comment by anhase** [comment]
Yes, let's do a new third page. We will need to write something to that
effect as we get our documentation together as it is.

**Comment by knod** [comment]
Sounds good, though I think we should stick to the first two for this PR - I think we should start with something fairly simple and refine/enhance it later as needed/desired. What if I change the current PR to point to a blank page, we merge that PR, and then others can work to fill in that file with information and make their own PR's? Just so we have the framework established.

**Comment by lianilychee** [comment]
Agreed!
