### ISSUE TITLE
Where should the 'Code for Boston' logo lead?

### ISSUE THREAD

**Issue by knod** [codeforboston/cliff-effects#138]
Right now it leads to the home page, but that seems confusing. Is there an official Code for Boston or Code for America page it could lead to?

**Comment by lianilychee** [comment]
http://www.codeforboston.org/

**Comment by knod** [comment]
The code hasn't been updated yet, so opening this until changes have been implemented.

**Comment by knod** [comment]
That was a good pull request, but actually only changed one of the menus. @shp54 could you grab the other menus too?

**Comment by knod** [comment]
Thanks!
