### ISSUE TITLE
Switch 'Result' page to table

### ISSUE THREAD

**Issue by knod** [codeforboston/cliff-effects#148]
Results page should show table shown by [this mockup, updated 10/31](https://docs.google.com/presentation/d/1hPZAPpPhdwpbn2Pv3LbjyXE3bekn_RG-CS8H0NT8rUM/edit#slide=id.p). It should include every program for which we're doing calculations.

For now KEEP THE GRAPH on that page too, just to aid in development. Also, we may want to consider keeping the graph, though hiding it, and allowing a user to reveal it if they so desire. The graph really does give a good idea of the progression of a program as income changes.

**Comment by lianilychee** [comment]
From [Issue 46](https://github.com/codeforboston/cliff-effects/issues/46)

> @WillMcIntosh: The [react-json-table](https://github.com/arqex/react-json-table) package looks promising. We just need to put our data into json format to be rendered by react. (It's currently not, to my knowledge)

**Comment by knod** [comment]
We did get a table. We're keeping the Results page till we figure out what kind of visualizations the project's clients are looking for.
