### ISSUE TITLE
Citizen Select

### ISSUE THREAD

**Issue by sashamaryl** [codeforboston/cliff-effects#152]
﻿

### Images:

<image src="https://lh4.googleusercontent.com/UW977CPtsOAL4B5Xh0VAQamc-ICmM2SNT1hML1OkvHtSAnz7drjp1E-MGK0OCc3sB4GQLHJXlFF5TGoCj9uaOBeJPoqcqIbU1uPC87BuFioE8TyvesQwaF8UxtUyvctkeUE5ZR8C" style="border: 5px solid lightGrey; margin-left:2rem;" width="250px" >
### Replicate:
1. Select any radio button other than the one that is initially default selected.

### Result I'd Expect:
 - Selected button would appear _'selected'_

### Actual Result:
 - None of the buttons can be selected

### Environment:
Operating system and version: 2008 macbook running Lubuntu 16.04
Browser type and version: Chromium, 62.0.3202.62 (Official Build)

App version or commit id at the time:

**Comment by knod** [comment]
Good find, but hold off on this one for now, folks! We actually may be throwing this one out completely.

**Comment by donblair30** [comment]
Ok Sasha hid this, I'll stand down for now.

**Comment by knod** [comment]
Closing until/unless citizenship becomes a thing.
