### ISSUE TITLE
Number fields accept multi-digit entry

### ISSUE THREAD

**Issue by sashamaryl** [codeforboston/cliff-effects#155]
﻿

### Images:

<image src="https://lh5.googleusercontent.com/-t7maFaB7YJo3U-tE9biYWhIODT_YG5f71uO6M_2gasLPzMgCSilfLptPaUZrm3QWVkjrAWof6Ft7_gbWq2myjoIvLXXFJzm0FERabsoPyxrFnWdcIJraGQ386LHUvN_CgNCJFnT" style="border: 2px solid lightGrey; margin:1rem;" height="200px">

<image src="https://lh3.googleusercontent.com/3Fc0HBPKN5_sYxRolwmoXp5kEIkfqbTmEjwcrg4ChGjvPyXb_ToNLV6de4ZqFTYMvJ1upp5idrLlWu8UtHPGYVlkkWkAfrSEFi8WrX1AdKiFk2yunL5lGVmfdJxPHoWddIA7MgsR" style="border: 2px solid lightGrey; margin:1rem;" height="200px" >

<image src="https://lh3.googleusercontent.com/LJZUdfOTWpvk6dxmf4DAQc9E0ZhFd5bvC_p1um4Pmhos_qNeLq3J362RWHyc8Bz3cG6UX9pepK5W3Zf_qlWpAB2I--LGaD_b71uRfOF4uDdBLwGVT00WdqzXKr2Q4TsLWerhfAKl" style="border: 2px solid lightGrey; margin:1rem;" height="200px" >

<image src="https://lh4.googleusercontent.com/rsA03UZcFYLXY5rbSPff5N92Ybx5BcTibd_L1moYNwBokPOZ-Yozs7J-bFRshYe3kWnCS5t38FXExLApqDpfjU1JShvm_9b2JElPZOP_dYd_riLZKx8vdY1RJpXfEvzeEnOqdDqv" style="border: 2px solid lightGrey; margin:1rem;" height="200px">

<image src="https://lh3.googleusercontent.com/DKvrVwiwf5mJPYKnilbIazZhZVSytw6HdGk5DlxLfhNzOKJZ1Kaun_mWUnGH0tgLpvQDzecdmr0e19I5r0wW3rXeGqdrO-KpwVgyeOsQG00v6AdS3HyzlH57jSYic6g8WyqcjXlE" style="border: 2px solid lightGrey; margin:1rem;" height="200px">

### Replicate:
1. Enter numbers into any number field.
2. Enter - + e .  [minus, plus, the letter 'e', period] or put a zero *before* the number.
3. Type as many numbers and symbols (-+e.) as you want into the field.

### Result I'd Expect:
One number in each little box.

### Actual Result:
Once the seal is broken with a symbol or a leading 0, you can keep typing in numbers and the symbols (-+e.) as long as you please.

### Update:
In checking this right before posting, it seems you are now freely able to enter multi-digit numbers into the fields, even without the symbol or leading zero to kick it off. Also, if you fill all cells and then type into the first cell, the two other cells extend outward. 

### Environment:
Operating system and version: 2008 macbook running Lubuntu 16.04
Browser type and version: Chromium, 62.0.3202.62 (Official Build)

App version or commit id at the time:

**Comment by knod** [comment]
I think this might be addressed really well by implementing the work we're doing on the client object. Latest demo: https://codepen.io/knod/pen/mqPLEB?editors=0010

**Comment by knod** [comment]
Just an update - partially being dealt with through #166, client object with always valid values. Will also be dealing with invalid inputs on the component end of things.

**Comment by knod** [comment]
Cash flow fields fixed by #272, I believe.
