### ISSUE TITLE
Remove percent of Federal Poverty Guideline/Level value?

### ISSUE THREAD

**Issue by knod** [codeforboston/cliff-effects#158]
It's been expressed by our clients that this isn't a particularly desired output/feedback. Given the facts below, it seems like removing it might be our best move. This could also open up an alternative - put the 'future earned income' question on the page with the results and have them be able to see their results update live as they change their projected income. We can put that in a different issue, though.

Explanation: While the Federal Poverty Guideline (its official name) is important to some of our calculations, there's no useful calculation to show a user's percent. The percent is determined by income, but each program has its own rules about what it counts as income. If we wanted to show one value, we could look into what the Census Bureau counts as income, but that isn't relevant to any of our other calculations.

**Comment by anhase** [comment]
Sounds good, remove it.

**Comment by knod** [comment]
I'll close. Will make an issue for removal. Feel free to re-open if needed.
