### ISSUE TITLE
ADD:  Page for user to review/confirm client information

### ISSUE THREAD

**Issue by lianilychee** [codeforboston/cliff-effects#16]
* [x] Mod status bar to account for the added page
* [x] Build the new page

STATUS BAR MOCKUP
![image](https://user-images.githubusercontent.com/6895034/30131486-ed217490-931a-11e7-8710-0c2fc1476d1e.png)

NEW PAGE SPEC

The new page should go after the MassHealth Qualifying Conditions Page, and before the Results page.  This allows the user to review/confirm inputs with the client, before jumping to the data viz.

![image](https://user-images.githubusercontent.com/6895034/30132332-01647aee-931e-11e7-99bd-d5fd1c09da79.png)

- Don't forget commas for household annual income value
- Copy for MassHealth negative:  "No qualifying conditions"

**Comment by knod** [comment]
Not sure at what point we'll get to it, but would it be useful for the values to be changeable in place? Or for each item to have a link to it's step in the form?

**Comment by carpeliam** [comment]
@knod thanks for the ideas! We can give it some thought. I think though that we can keep this issue scoped to not include those details.

**Comment by knod** [comment]
I completely agree, you got my intention exactly. As you said, not anything to require in this issue.

**Comment by shp54** [comment]
https://github.com/codeforboston/cliff-effects/pull/73

**Comment by knod** [comment]
Just to understand more clearly, is this part of the MVP, or a piece that needs some work separate from that?

**Comment by lianilychee** [comment]
The latter.  Jonathan and I were starting to familiarize ourselves with the codebase by watching Shameek tackle a simple issue.

**Comment by knod** [comment]
I'm not sure this one is closed yet, as this page isn't fully functional. To close this issue, we either get rid of it, or complete it.

**Comment by knod** [comment]
Page was removed.
