### ISSUE TITLE
'About' Page Content

### ISSUE THREAD

**Issue by ManickYoj** [codeforboston/cliff-effects#171]
The current 'About' page is blank. Either

a) We should delete it.
b) We should populate it.

If we populate it, I suggest a prose version of the following:
* What the tool is for => calculating the effect of income changes on gov benefits 
* Who the tool is for => case workers, primarily.
* How does it work => Input client data, follow along, get results
* Who made it/how do I submit bugs? => CfB/email ___ where ___ is likely @knod 

Could be structured as an FAQ along these lines. Doesn't need to be though.

**Comment by knod** [comment]
Just in case of buses, for the last item, I propose:
- Who made it/how do I submit bugs? => link to github issues page

**Comment by ManickYoj** [comment]
Thought of that - I don't know if we want case workers to directly insert problems to our technical issues board. I figured we probably want a person as a filter between them and the issues board. Not positive - that's just my 2 cents.

**Comment by knod** [comment]
Fair point.

**Comment by lianilychee** [comment]
Andrew's working on the prose, I believe.  I also agree with Nick's assessment re: person filter, and the user testing process Andrew's mapped out allows for that.

**Comment by anhase** [comment]
I'll have a draft of this tomorrow afternoon. What's the best way to submit the prose? Just as a comment to this thread?

**Comment by knod** [comment]
@anhase Let's discuss this on slack since it might get complicated depending on what format it's in right now.

**Comment by anhase** [comment]
Okay.

**Comment by knod** [comment]
@anhase When you have one ready, put a link here to the text that will be the content.

**Comment by knod** [comment]
Doc here: https://docs.google.com/document/d/1mZNud_JvnC33oNIJBXK_MeBYIuqchmJ3-bfHglKgQbs/edit?usp=sharing

Most needed now are names of Code for Boston contributors. @emily-wasserman, @isaacchansky, @carpeliam: Any idea how we can gather a more complete list of those who contributed?

**Comment by carpeliam** [comment]
I spoke with Andrew and gave him the names of people I can remember - I'm removing myself from the list of assignees, but let me know if I can help more.

**Comment by ManickYoj** [comment]
Resolved by @anhase some time ago.
