### ISSUE TITLE
Footer Clean-Up

### ISSUE THREAD

**Issue by ManickYoj** [codeforboston/cliff-effects#172]
The footer currently looks like this.

![selection_001](https://user-images.githubusercontent.com/2252820/32644059-4272f800-c5ad-11e7-8a15-5a47095d1775.png)

The links under 'About' and 'Services' are duds that do not work. I do not believe we have any intention of making them work. Assuming that is so, let's remove them, and simply leave 'Cliff Effects Tool'.

We probably don't need the footer to take up quite so much space (padding) either, considering its lack of utility. Once the content is changed, make some reasonable decisions to make it look nice.

**Comment by knod** [comment]
Regardless of whether we remove other things from the footer, it occurs to me that we can free up some room at the top by adding the footer to other pages and moving the 'About' link to it. Might also be a good place for the 'Feedback' button mentioned in #133.

**Comment by knod** [comment]
Any opinions on keeping the 'About' page link in the footer?
