### ISSUE TITLE
Track down new console warning

### ISSUE THREAD

**Issue by knod** [codeforboston/cliff-effects#175]
### Replicate:
1. Go to the first form page
2. Look in the browser console

### Result I'd Expect:
- Nothing in the console

### Actual Result:
- 'Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `StepGroup`.'

### Environment:
Operating system and version: OSX 10.11
Browser type and version:  Chrome v61.0.3163.100

App version or commit id at the time: commit 4c744c4449cc4d09125a97fbb7392b2f8992cd94

### Other Notes
This happened in some past commit, probably before a4b539e54348893064235f14f6e02aeb209f734c. Find where it happened and fix it.

**Comment by ManickYoj** [comment]
Ah. This is a pretty common bug. Whenever React components are created in a loop of any sort, they're supposed to have a `key` prop passed to them, unique with respect to their siblings in the loop. Typically, the solution is to have the loop pass the current index to the children as their `key`.

**Comment by knod** [comment]
Yeah, but before now there was no warning, so something changed. Maybe someone made a loop, but I'd like to check it out.
