### ISSUE TITLE
Consistently using client identifying information

### ISSUE THREAD

**Issue by lianilychee** [codeforboston/cliff-effects#184]
Upon intake, we ask for the client info (name, dob, etc.) but when we hit "submit," a default name + client info is displayed.

- [ ] Remove default client info page
![image](https://user-images.githubusercontent.com/6895034/32703768-a0202546-c7c8-11e7-9909-f4d33bdca131.png)

- [ ] Make sure that nav has correct name from form
![image](https://user-images.githubusercontent.com/6895034/32703776-bfc752ac-c7c8-11e7-84dc-c4b566009a0c.png)

**Comment by knod** [comment]
Since we're not doing client intake anymore, I'm retiring this issue.
