### ISSUE TITLE
Home page redesign

### ISSUE THREAD

**Issue by lianilychee** [codeforboston/cliff-effects#185]
Mockup:
![image](https://user-images.githubusercontent.com/6895034/32857458-e0864f76-ca15-11e7-9cd7-f1ffcbaa542f.png)

Actions:
- [x] Hide the header on the home page
- [x] Make [this SVG](https://vectr.com/lianilychee/aFpUTVlyM.svg?width=1920&height=1080&select=aFpUTVlyMpage0) the background image (you will have to right-click save-as the image).  [StackOverflow on how to make a background image in React](https://stackoverflow.com/questions/29322973/whats-the-best-way-to-add-a-full-screen-background-image-in-react-native)
- [x] Change the header + footer color to #00aaa1
- [x] Add title + subtitle.  Text color is #efefef
- [x] Build buttons.  Background color is #ffffffc8.  Text color is the original teal (#00b9b0)
- [x] Add disclaimer.  Text color is #efefef 

This issue is merged with #200 

Defunct as of 11/15
~- [ ] Remove giant CfB logo~
~- [ ] Remove "intake a new client to begin" and associated button~
~- [ ] Merge New Client Intake page content with Home Page~
~- [ ] Remove Client Avatar URL field~
~- [ ] Remove New Client Intake page~
~- [ ] Modify header:  "Home" -> "Intake New Client"~

Defunct as of 11/13
~Landing page needs to be redesigned such that:~
~- Content fills height perfectly, so no scrolling~
~- The awkward whitespace is filled (perhaps with the 'about' content?~
~- The top teal section is not so aggressively large (perhaps change the logo to match the one in left of nav bar, and scale down in size)~

**Comment by lianilychee** [comment]
Thoughts from @sashamaryl 
>remove white bar maybe open up between logo and title
>possibly make whole middle white & reverse out logo and title etc

**Comment by lianilychee** [comment]
Sorry @scapp281 - spec change, just fyi.

**Comment by knod** [comment]
I suggest just getting rid of the header on the home page.
