### ISSUE TITLE
Various small semantic changes

### ISSUE THREAD

**Issue by lianilychee** [codeforboston/cliff-effects#188]
[See last comment for reason this is open]

Please change the verbiage in the following:

- [x] Current Expenses section: "LEGALLY OBLIGATED Child support paid out" -> "Legally obligated child support"
- [x] Current Household Income section: "Expense Type" (table header) -> "Income Type"
- [x] Current Household Income section: "Child support coming in" -> "Child support received"
- [x] Future Household Income section: "Expense Type" (table header) -> "Income Type"

**Comment by knod** [comment]
A couple concerns:
- 'Legally obligated' needs to be emphasized somehow and, if I recall correctly, the text there is already bold.
- 'Paid' can mean either something I paid or something that was paid to me and is not clear, though I realize it is in expenses. Given that keeping track of everything can be confusing in these situations, I just like to make language as clear as possible.
- I'd suggest 'Child support received'
- I'm sorry my capitalization was inconsistent originally. I say we only capitalize the first letter in each input row label.

**Comment by knod** [comment]
Regarding item 1:
> Current Expenses section: "LEGALLY OBLIGATED Child support paid out" -> "Legally obligated child support"

In at least one case, I've seen the user confused about whether the child support is paid by the client or to the client. This is one we might want to watch.

Not sure if it's quite time to re-open it, but not sure how else to remember to keep an eye on it.

**Comment by knod** [comment]
It does look like it still causes confusion. I'm going to create a new issue where we can discuss how to clarify that.
