### ISSUE TITLE
Remove need for `Results.js`

### ISSUE THREAD

**Issue by ManickYoj** [codeforboston/cliff-effects#196]
## Purpose
`Result` is a class we use to format results from benefit calculations. @knod has opined we probably don't need it anymore and we can probably just have benefit calculations return numbers.

Note: this is a pure refactor. Probably not the highest priority for now.

## Implementation
To make this happen, we just need to track down all the imports of `Result` and rewrite the code that uses it to work without the `Result` file.

**Comment by knod** [comment]
A little bit more than that is required. We also need to track down the places that use `Result` and have them do something else instead. Those are things that make the results tables and things that display status in the right-hand alert bar. What I suggest is that we have benefit functions return values, and have a helper function that determines what to show for the alerts based off of those returned values.

This also requires us to be able to calculate both previous and future benefit values, which requires us to use 'current' and 'future' differently in the benefit calculations. And all that ties into having a controlled client object. So. We're getting there.
