### ISSUE TITLE
'Erase Data' type button at the end to reset everything.

### ISSUE THREAD

**Issue by knod** [codeforboston/cliff-effects#201]
All it needs to do is refresh the page. That will restore to a clean state.

Button wording suggestions: 'Reset', 'Reset data', 'Clear data', 'Restart', 'Finish and erase data'

**Comment by knod** [comment]
I think that may have been by accident. This is not the 'enter button' issue.

**Comment by sashamaryl** [comment]
yes accident. thanks for catching.

**Comment by knod** [comment]
From what I think I remember, people were into this, so removing the 'discussion needed' tag.
