### ISSUE TITLE
Combine 'Future Income' section with 'Results' section

### ISSUE THREAD

**Issue by knod** [codeforboston/cliff-effects#206]
This should be hooked up to allow the user to see their results updating live as they change the value. If I recall correctly, that functionality should take almost no adjustment, if any.

Proposed names for the section:
- 'What if'
- 'Finish'
- Keep it 'Result'
- 'Projection'

Feel free to add more suggestions in this thread!

**Comment by sashamaryl** [comment]
decided on "Predictions" for the step-bar name.
