### ISSUE TITLE
Replace household form section with individual member data collection

### ISSUE THREAD

**Issue by knod** [codeforboston/cliff-effects#208]
- [x] Start with one member
- [x] Allow the addition of more members
- [x] Allow the deletion of members
- [x] For each member, collect:
   - [x] Their role. Ways to go about it:
      - Dropdown to choose 'Head of household', 'Spouse of head of household', or 'Member'.
      - Just provide the ability to select one member as a 'head' and one member as a 'spouse'.
      - Make the first member the 'head' automatically. Provide an option to select the 'spouse'. Don't allow the first member to be deleted.
   - [x] Age (number input).
   - [x] If they have a disability or not (checkbox).
   - [x] Are there more? Will need to double check the current questions. [Edit: this will be it for now]
- [x] Integrate new system with other code that uses those values:
   - [x] Expenses page
   - [x] housing.js
   - [x] snap.js

**Comment by anhase** [comment]
Under role, I might frame these as "Parent (Head of Household),"
"Grandparent," "Child," or "Other relationship"

**Comment by knod** [comment]
@anhase: Even if none of the other roles are relevant?

**Comment by knod** [comment]
@anhase: That is, it's not going to matter to us if they're a 'grandparent' or a 'child', and if we included those roles, what else would we need to include for our clients to feel like they have the ability to answer that question. Would we need to include stuff like 'foster child', 'brother', etc.? That's why one of the suggestions was just to have the ability to select the head of household's spouse instead of offering several selections.

**Comment by knod** [comment]
Though the design of this is still undecided, the functionality should be there.
