### ISSUE TITLE
Create function: string to decimal value

### ISSUE THREAD

**Issue by knod** [codeforboston/cliff-effects#225]
Make a function that takes a string value. You check that the value contains only a simple positive decimal number. No negatives or other fancy scientific notation stuff. If it's good, you turn it into a decimal number and return that number. Otherwise, return null. Don't change the number.

Regex for checking for anything other than digits and a decimal: `invalidPosNumRegex = /^([0-9]|\.)+$/g;`

Just make it in a codepen or jsfiddle, ready to be pasted where we then decide to put it.

**Comment by knod** [comment]
Also, three more things:
- The string is allowed to represent an integer.
- The returned value is allowed to be an integer.
- The string is not allowed to contain more than one period character.

**Comment by knod** [comment]
Do #227 first.

**Comment by sashamaryl** [comment]
this function on codepen

https://codepen.io/sashamaryl/pen/KyxMLL
