### ISSUE TITLE
Create function: decimal to string money value

### ISSUE THREAD

**Issue by knod** [codeforboston/cliff-effects#226]
Make a function that takes a [valid] positive decimal number, rounds it to two decimal places, and turns it into a string that contains at least 'd.dd' where 'd' means digit. It has to make sure to contain three digits, even if they're 0's

Just make it in a codepen or jsfiddle, ready to be pasted where we then decide to put it.

**Comment by sashamaryl** [comment]
this function on codepen: 

https://codepen.io/sashamaryl/pen/wPEWLY

**Comment by knod** [comment]
Does what it needs, ready to be used for #247.
