### ISSUE TITLE
Create function: check for valid positive decimal number

### ISSUE THREAD

**Issue by knod** [codeforboston/cliff-effects#227]
Make a function that takes a string and returns a boolean. It should return `false` if the string contains any non-digit or non-decimal characters, or has more than one decimal. Otherwise, return `true`. It can also be an integer.

Regex for checking for anything other than digits and a decimal: `invalidPosNumRegex = /^([0-9]|\.)+$/g;` (not sure that this checks for more than one period character)

Just make it in a codepen or jsfiddle, ready to be pasted where we then decide to put it.

**Comment by sashamaryl** [comment]
this function on codepen:

https://codepen.io/sashamaryl/pen/OOoXKw

**Comment by knod** [comment]
Great! Now to be written into #244!
