### ISSUE TITLE
Clearly express the valid values for each client property

### ISSUE THREAD

**Issue by knod** [codeforboston/cliff-effects#243]
Perhaps on the client default object.

**Comment by wacii** [comment]
Once more inputs are validated, you might maintain a file for the validations like 'src/utils/valueFixers.js'. Code is less likely to become out of date than comments.

**Comment by knod** [comment]
@wacii There's a file for that ('src/utils/validators.js'), but validation is happening in components - no invalid values will be passed to the client object. Part of why it's handled there is to allow easier feedback to the user about invalid values. We can consider using a 'valueValidators.js' kind of thing, but it seems like it may add unnecessary complexity/abstraction. Maybe seeing it in action would be different.

**Comment by knod** [comment]
Fixed by #277
