### ISSUE TITLE
Bug on Reasonable Unreimbursed Non-Medical Child(ren) Care in Current Household Expenses

### ISSUE THREAD

**Issue by johnschoeman** [codeforboston/cliff-effects#248]
### Images:
![image](https://user-images.githubusercontent.com/16049495/33379992-aacd277e-d4e7-11e7-8333-e611189ffb90.png)

![image](https://user-images.githubusercontent.com/16049495/33380069-e9a22ef4-d4e7-11e7-8a31-3dc5601e6ba2.png)

### Replicate:
1.  have an under 12 household member in house hold
2.  go to Reasonable Unreimbursed Non-Medical Child(ren) Care
3.  input into Income made possible by child care expenses

### Result I'd Expect:
- input updates, saves to calculator

### Actual Result:
- ungraceful error, see screen shot

### Environment:
Operating system and version: OS Sierra 10.12.6
Browser type and version: Chrome Version 62.0.3202.94 (Official Build) (64-bit)
App version or commit id at the time: f98cb3cf712a4a0cc1f43871271d242df1a1f22d

**Comment by knod** [comment]
Awesome find! I suspect it's a typo in one or more of three places. Either in CLIENT_DEFAULTS, valueFixers, or CurrentExpenses in various folders. We'll track it down!

**Comment by knod** [comment]
Commit b6d2bd4 fixed

**Comment by knod** [comment]
Oops, not merged yet.
