### ISSUE TITLE
Link member data design ideas to this issue

### ISSUE THREAD

**Issue by knod** [codeforboston/cliff-effects#276]
I think there were some discussions about design ideas for the 'Household' page, right? Could someone put together an image of what those thoughts look like at the moment and/or notes on the discussion?

Were there design ideas about other aspects of the site? If so, could someone make an issue for each one so it can have images linked to it too?

**Comment by willmillar** [comment]
I wasn't involved in the original discussion, but I'm happy to help make a sketch or a mockup! I'll be at CFB tomorrow night.

**Comment by knod** [comment]
This seems to have not moved forward. For now, we'll keep the design as it is.
