### ISSUE TITLE
Migrate Inline Styles to CSS File(s)

### ISSUE THREAD

**Issue by ManickYoj** [codeforboston/cliff-effects#286]
Part I of Epic #288 .

We're standardizing our styling practices to use CSS files over inline styling. To work on this, grab any old JSX file that hasn't been done yet, and migrate the inline styles into the CSS file, ideally checking first to make sure there's no CSS class that serves the intended purpose.

**Comment by sashamaryl** [comment]
# 
# hi
making my way through the css today ...

I'm appreciating more then ever just how strict semantic (and anything else like it) is. Other than those inline styles, semantic always is 'more specific' and its styling always wins out. Always. 

In other words, CSS on its own isn't going to do what we want it to do here. 

We still can and need to get things wrangled. I'm thinking that we should lean into semantic ("warning" "success!"), really try to make the most of what it does out of the box, and when really necessary we can use a style={{}} or an !important (yes !important works, but it doesn't really scale, does it?)

We could consider going totally our own css way, re-styling things etc, but we are thoroughly entangled with semantic. I think it would take a long time and would make a bigger mess than we got now.

Same for loading up the theme editors from semantic. Looking into it, very cool idea, would be great, but way too many bees for that honey. 

Thoughts? Things you know that I do not yet know?

**Comment by knod** [comment]
@sashamaryl We can also add our own classes to our components and elements and, in that way, win the css selector war on our terms.

**Comment by knod** [comment]
A warning to whoever takes this on - you're going to be working on files other people are working on, so merge conflicts may come up a lot.

**Comment by sashamaryl** [comment]
Sure, components & classes may be the way to organize ourselves. I would really like to get some heads together and talk through it.

**Comment by WillMcIntosh** [comment]
@sashamaryl I'm available to meet up this weekend if you wanted to put some sort of game plan together.

**Comment by sashamaryl** [comment]
Great! I'll slack ya.

**Comment by dylanesque** [comment]
I pored over the containers and components and was surprised to see that HomePage.js was the only file I can find that was really laden down with inline styles. There are others out there, but only one or two per page, at maximum. Do we need to remove literally every inline style from the code-base, or is this issue effectively closed.

**Comment by ethanbb** [comment]
@dylanesque I would lean toward **yes**, let's pull out all the inline styles. There may be only 1 or 2 per file, but I just took a look and there are still a significant number in total. It would be really nice to have them all in one place, so it's easier to look at the styles in the app as a whole and simplify things and/or refactor if we feel the inclination.

That being said, if you're getting tired of munging CSS, maybe someone else would be willing to finish the job. Any takers?

**Comment by dylanesque** [comment]
No, it's no trouble at all. I'll ping you guys if I happen to get tired of this, but I'm nowhere near that point.

**Comment by knod** [comment]
Being taken care of in #288
