### ISSUE TITLE
Scrolling bug due to header menus

### ISSUE THREAD

**Issue by wacii** [codeforboston/cliff-effects#289]
Set the window height to ~950px, so the page doesn't quite fit in the screen, then try and scroll down. The page will briefly scroll before jerking back up to the top. This is due to a page height difference introduced by `<MainMenu>` and `<FixedMenu>`.

This can be fixed by making the page heights equal (and smoothing out the transition), but I would instead suggest removing the fixed menu. The pages are never long enough to really need it and the menu transition is kind of choppy on my iPad anyways.

**Comment by wacii** [comment]
The design has been updated, so the stutter no longer appears at ~950px for most of the form pages. Still easy to reproduce though; decrease the window height until the vertical scroll bar just appears, then try and scroll.

**Comment by ManickYoj** [comment]
I agree with @wacii that we have no pages that really need a fancy fixed menu transition. Better to just have a smooth transition. I'll change this presently.
