### ISSUE TITLE
Turn existing suggestions on PR #280 into issues.

### ISSUE THREAD

**Issue by knod** [codeforboston/cliff-effects#291]
(Do this even if/when the PR has been closed) Turn these each into an issue for the 'About' page. I think they all may be beginner friendly. I'm going to fix the other problem with the page and then merge and then these improvements can be made. Some of these may be group-able.
- [ ] https://github.com/codeforboston/cliff-effects/pull/280#discussion_r155122402
- [ ] https://github.com/codeforboston/cliff-effects/pull/280#discussion_r155123692
- [ ] https://github.com/codeforboston/cliff-effects/pull/280#discussion_r155131091
- [ ] https://github.com/codeforboston/cliff-effects/pull/280#discussion_r155131324
- [ ] These three together (consult with @anhase for names for links): https://github.com/codeforboston/cliff-effects/pull/280#discussion_r155131423, https://github.com/codeforboston/cliff-effects/pull/280#discussion_r155131449, https://github.com/codeforboston/cliff-effects/pull/280#discussion_r155131469
- [ ] https://github.com/codeforboston/cliff-effects/pull/280#discussion_r155131656

**Comment by lianilychee** [comment]
Closing, because (a) these are all already being addressed in #290 (I'm working on that Travis compile error), and (b) I think it's excessive to to make an issue, about making more issues, when this is already a process handled as part of PR review.
