### ISSUE TITLE
Add warning about loss of data when page is being refreshed

### ISSUE THREAD

**Issue by knod** [codeforboston/cliff-effects#296]
We used to have this way back near the very beginning, so if it doesn't come to us straight away, we can check out the files from the earliest commits.

**Comment by wacii** [comment]
Would it be better to save the data between sessions?

**Comment by knod** [comment]
@wacii: We're not going to be saving any data, partially because this is sensitive information and we'd have to jump through a whole lot of hoops to be able to store that kind of information.

**Comment by wacii** [comment]
Even if its just stored on the device?

**Comment by knod** [comment]
It was enough of a question that it was decided it wasn't worth going into.
