### ISSUE TITLE
Household page vibrates 

### ISSUE THREAD

**Issue by sashamaryl** [codeforboston/cliff-effects#300]
The household page vibrates like crazy when you do the two-finger scroll-down on a touch pad. Other pages don't seem to do this.

I'm on an ancient macbook pro, running ubuntu (xubuntu) 16.04 

latest commit c900b0a

**Comment by knod** [comment]
Hmm, I don't get the same behavior on newer mac book pro

### Environment
MacBook Pro 10.11.6
Chrome 62.0.3202.94

@sashamaryl: What version of what browser are you running?

**Comment by wacii** [comment]
Related to #289?

**Comment by knod** [comment]
@wacii: That looks like a good lead. Hmm, maybe because of that header, certain window heights 'shake'. Or other factors.

**Comment by sashamaryl** [comment]
I am on chromium Version 62.0.3202.94. 

Re #289, I've been getting a pretty rough 'popping' header transition over here, myself. Every page, not just household.

**Comment by knod** [comment]
@sashamaryl: Yeah, the fixed header thing has always been an issue from what I recall.

**Comment by wacii** [comment]
What is your window height? If it's the same issue, that is more important than which browser you're using.

**Comment by knod** [comment]
I think that was meant for @sashamaryl.

**Comment by sashamaryl** [comment]
Sorry for delay! Not sure the size and can’t recreate now unfortunately, but it happened a couple times so I imagine will happen again…sorry about that, should have thought of noting the size at first.

**Comment by wacii** [comment]
@sashamaryl I updated the steps to reproduce #289. Could you try it out to see if its the same bug?

**Comment by sashamaryl** [comment]
just happened again: 

at height 789px

at widths from max (1430px) down to about 880px I get the shakes

at 880px in width the step bar disappears and the shaking stops. Perfect window fit, no scroll. 

When I add household members, I'm back to the regular scroll with the fixed menu bump, at all widths. Stepbar remains hidden at the narrower width. 

(I have to run now. I will try your steps later on! Sorry :/.)

**Comment by wacii** [comment]
@sashamaryl I checked out the household page using the dimensions you provided, and it appears to be the same issue.
