### ISSUE TITLE
Test snap.js with sample clients

### ISSUE THREAD

**Issue by knod** [codeforboston/cliff-effects#315]
Add sample client tests
- [x] CLIENT_DEFAULTS
- [x] CLIENT_ROW_3
- [x] CLIENT_ROW_4
- [x] CLIENT_ROW_5
- [x] CLIENT_ROW_6
- [x] CLIENT_ROW_7
- [x] CLIENT_ROW_8 (row 8 may need to be removed because it doesn't have SNAP benefits)
- [x] CLIENT_ROW_9
- [x] CLIENT_ROW_10

**Comment by johnschoeman** [comment]
Added tests for basic calculation of snap benefits with default client.  Would be good to have calculations verified against MA calculators and to add more test cases.

**Comment by knod** [comment]
This PR didn't use sample clients yet and it'd be good to have more extensive testing before closing. Definitely a good first step, though. Perhaps we can assign more folks to this one.

**Comment by knod** [comment]
This was covered in more detail in #329 as well. We'll take care of sample row 8 some other time.
