### ISSUE TITLE
Unit test some utils files

### ISSUE THREAD

**Issue by knod** [codeforboston/cliff-effects#361]
- [x] src/utils/prettifiers.js
- [x] src/utils/validators.js
- [x] src/utils/valueFixers.js

**Comment by microcat49** [comment]
I was looking at the functions isPositiveNumber() isPositiveWholeNumber() in src/utils/validators.js. 

 isPositiveNumber() will return whether or not a string is a number. 

isPositiveWholeNumber() will return whether or not a string is a whole number. 

But neither will check if the string is even. I looked through the code I'm not sure if they're suppose too. 

I was wondering should I change the names to ease confusion or make the function check for even numbers?

**Comment by knod** [comment]
@microcat49: We don't need anything to check for even numbers. What are you finding confusing about the names? What in the names implies that they should be returning even numbers?

**Comment by microcat49** [comment]
@knod My bad I'm not sure why I thought that.

**Comment by knod** [comment]
@microcat49: No worries, always good to have a fresh and skeptical eye on things.

**Comment by knod** [comment]
I believe #366 closed this.
