### ISSUE TITLE
When there's no data download should the "Download Data" button be grayed out?

### ISSUE THREAD

**Issue by kalpana-k** [codeforboston/cliff-effects#398]
### Replicate:
1. Home page
2. Get started

### Result I'd Expect:
- There's no data to download. The button should be grayed out so the user cannot click on it.

### Actual Result:
- when the user clicks on the button, a default/empty json file downloads.

### Environment:
Operating system and version: 
Browser type and version: 

App version or commit id at the time:

**Comment by knod** [comment]
We no longer download data, though we do allow people to give feedback, and they can do that anytime. We're working on doing a plain old text version of the results and we may make that printable, but this particular issue is out of date. It was a great question at the time, so thanks!
