### ISSUE TITLE
MOD: Data visualization 

### ISSUE THREAD

**Issue by lianilychee** [codeforboston/cliff-effects#40]
- [ ]  Add a "you are here" vertical red line to data viz, showing where the client is on the income axis
- [x]  Add thousandths separator to x- and y-axis numbers

**Comment by zzyyfff** [comment]
Should we change the type of graph to a "stacked area graph" ?

see: http://www.datavizcatalogue.com/methods/stacked_area_graph.html
![image](https://user-images.githubusercontent.com/7986137/30622266-74df5c72-9d7e-11e7-9f10-e285986ea5a5.png)

**Comment by zzyyfff** [comment]
Obsoleted from the current plan
