### ISSUE TITLE
Abstract components (with sensical folder structure)

### ISSUE THREAD

**Issue by knod** [codeforboston/cliff-effects#405]
(*Relatively* beginner friendly) There are many components on each src/forms script. It would help testing, etc., if some of these were abstracted. It's not friendly to a very new coder, but if you have a bit of coding experience, you won't have to know the codebase well in order to do this.

**Comment by nicklee100** [comment]
this is being included under the issue 'project' and "Component refactoring components (maybe organize by functional vs. presentational?)"

**Comment by knod** [comment]
Killing this wishlist item. We do this as we go somewhat and will do more as it comes up, but this is no longer referred to.
