### ISSUE TITLE
Feedback as embedded google form or something else more useful?

### ISSUE THREAD

**Issue by knod** [codeforboston/cliff-effects#423]
I think we could find a way to attach a file, or include the data in some other way, but I'll have to look into it.

**Comment by ethanbb** [comment]
Update: we are going to try creating our own form instead of using a Google form. Then we will either use a tiny server to send the form data over email, or add it to a Google spreadsheet using Apps script.

**Comment by ethanbb** [comment]
Branch with development of form and request to send data to a google spreadsheet: https://github.com/ethanbb/cliff-effects/tree/feedback-form

**Comment by knod** [comment]
Fixed with #465
