### ISSUE TITLE
If someone deletes a number, the field should then contain a 0 on blur.

### ISSUE THREAD

**Issue by ethanbb** [codeforboston/cliff-effects#425]

**Comment by ethanbb** [comment]
Pro: maybe aligns with the action of erasing an entry on a paper form, where blank rows are assumed to be 0?
Con: might cause mistakes/frustration if someone accidentally deleted the wrong row. Although I wouldn't necessarily expect the form to help me out if I did that.

**Comment by knod** [comment]
I don't currently remember any other arguments against this. I think I too would expect deleting everything to turn it into a 0 value.

**Comment by ValerieKenyon** [comment]
I'm interested in taking a look at this issue (but I may not be able to do much yet).

**Comment by ValerieKenyon** [comment]
I've played around with inserting and deleting numbers.  The input field seems to "remember" the very last digit that was deleted, and auto-fills the other two fields based on that last digit.  But if the last digit deleted is a zero, the auto-fill then uses (and returns) zero.
