### ISSUE TITLE
Clicking on field with the default 0.00 should turn blank

### ISSUE THREAD

**Issue by nicklee100** [codeforboston/cliff-effects#426]
Clicking on data entry field that contains the default value 0.00 should turn blank. If the user clicks away without  entering it should go back to 0.00.

**Comment by knod** [comment]
Assigned to Caitlin, but can't find her username yet.

**Comment by caitlinvinci** [comment]
This is Caitlin/my username.

**Comment by caitlinvinci** [comment]
Taken care of - formHelpers, handleFocus. ed8682ff6303bc0dd3290e35973a127c76f88fce
