### ISSUE TITLE
Increase visibility of "Income made possible by child care expenses"

### ISSUE THREAD

**Issue by ethanbb** [codeforboston/cliff-effects#437]
Field in "expenses" form that is visible when the household contains a child under the age of 13.
We said we would put this in a new section to try to increase its visibility, since it has a major impact on the future income calculation.

**Comment by ethanbb** [comment]
@wacii suggested having a yes/no switch asking "Does childcare allow you to make additional income?" before the field appears.

**Comment by knod** [comment]
We may keep any 'abandoned' value in the component itself. The advantage is we keep logic and view separate. The disadvantage is that the 'abandoned' value will be erased when the component is unmounted. Decision is yet to be made.
