### ISSUE TITLE
Add regression tests for user interface components

### ISSUE THREAD

**Issue by ethanbb** [codeforboston/cliff-effects#446]
Inspired by #443. Use enzyme (including click simulation) to verify that things like editing/focusing/blurring each type of inputs, clicking buttons, navigating, and throwing errors do what we want them to. Start with ManagedNumberField, CashFlowRow, MonthlyCashFlowRow, etc.

Branch: https://github.com/ethanbb/cliff-effects/tree/test-interactions

**Comment by shp54** [comment]
https://docs.google.com/document/d/13BtVvZi2C6lusC5xUeTKxYP9LpLWW5geuaW903UE7ts/edit

Writeup so far on UI testing

**Comment by knod** [comment]
This is that same document, but in the google shared folder for Cliff Effects/Technical/Test: https://docs.google.com/document/d/1IjLVvwEg0RRn5bz2ArswMZ6ERp2q0AjO9xvjLv1luxc/edit?usp=sharing

**Comment by knod** [comment]
There's some stuff in there that may be worth pursuing, btw, like the SNAP stuff. Could swear I've never seen it before in my life.

**Comment by knod** [comment]
This is still ongoing

**Comment by knod** [comment]
Hmm, I think the 'testing' project is a good place to keep the link to the doc and issues could contain more specific tests.
