### ISSUE TITLE
Section 8 Housing Voucher benefit calculations

### ISSUE THREAD

**Issue by knod** [codeforboston/cliff-effects#46]
#All of these must be in terms of the fields used in the form, even when they're broken up into parts to accommodate other programs' needs.

CALCULATIONS
- [x] Find documentation for and determine calculations for this benefit program's gross income
  - Gross income earned and unearned income with no deductions ([here](https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=ccd82d677e91fcd79f0e53edf0456abf&mc=true&n=sp24.1.5.f&r=SUBPART&ty=HTML#se24.1.5_1609), I believe)
- [x] This will be taken care of through the exclusions issue, #207  ~Find documentation for and determine calculations for this benefit program's income exclusions (to determine net income) (documentation: [In section 5.3, Income Exclusions](https://www.hud.gov/sites/documents/DOC_11749.PDF))~
- [x] Find documentation for and determine calculations for this benefit program's values for these income deductions ([here](https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=ccd82d677e91fcd79f0e53edf0456abf&mc=true&n=sp24.1.5.f&r=SUBPART&ty=HTML#se24.1.5_1611), though not as clear as the hud portal pdf, unfortunately):
  - [x] A. Dependent Allowance
  - [x] B. Child Care Expenses
  - [x] C. Handicapped Assistance Allowance
  - [x] D. Medical Expenses
  - [x] E. Elderly Family or Disabled Family Family
- [x] Adjust forms to match the needs of this program (see the [form-question-compling google spreadsheet](https://docs.google.com/spreadsheets/d/1hvMqhOtIaQr6uYyc-nizXLp8cNtKuajuEeJj6Ysbw08/edit#gid=0)).

DISPLAY RESULTS -  *moved to [Issue 148](https://github.com/codeforboston/cliff-effects/issues/148)*
~- [ ] Remove graph~
~- [ ] Put accounting tables in results page, a la ~[this mockup](https://docs.google.com/presentation/d/1PtWZizzgNBKxWz8g98jiIUTcHrl0PE-tWuA9CgqGc6M/edit#slide=id.g25a018bcbd_0_520) (slides 4-5)~ [this mockup, updated 10/31](https://docs.google.com/presentation/d/1hPZAPpPhdwpbn2Pv3LbjyXE3bekn_RG-CS8H0NT8rUM/edit#slide=id.p)~

Resources (documentation found):
- Our [spreadsheet](https://docs.google.com/spreadsheets/d/14FFcrEwZVTJDc00X7V4XkicE3NYVVF0lijV1jMLe--Y/edit#gid=162959319) now contains a decently organized set of summations and resources
- http://www.tacinc.org/media/58886/S8MS%20Full%20Book.pdf
- ~~https://portal.hud.gov/hudportal/documents/huddoc?id=DOC_11749.pdf (contains the date 2017)~~ [**Edit:** link seems to go to the right doc in Firefox, but not Chrome] ~~Apparently not working right now. I've downloaded what I think is a cached version of the document, but we can try [this](https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=ccd82d677e91fcd79f0e53edf0456abf&mc=true&n=sp24.1.5.f&r=SUBPART&ty=HTML) instead for now.~~
- https://www.hud.gov/sites/documents/43503C5HSGH.PDF (Chapter 5 of, probably, the current available version of the 11749 pdf from what I can tell. Links to all sections [here](https://www.hud.gov/program_offices/administration/hudclips/handbooks/hsgh/4350.3). If you need to find it again, try going to the HUD site and using their search to look for `4350.3 Rev-1` or `4350.3 Full Version`. Secondly, if that doesn't work you can try calling someone at HUD. I looked in the 'Contact Us' section, under 'Toll Free Numbers' and followed the 'Publications, Forms, Issuances' link. Pro tip: offices found through 'Policy and Research' were not able to help.

**Comment by knod** [comment]
Both income exclusions and inclusions are fairly convoluted. It's unclear if there's a point in making a form question for each of these items, if there should be definitions pages/elements that can more extensively describe the details of a question, or if this knowledge should be left up to the user to know, especially for the first prototype. Any input on this would be welcome. The income details can be seen in ~~https://portal.hud.gov/hudportal/documents/huddoc?id=DOC_11749.pdf~~ This document has disappeared. There's https://www.hud.gov/program_offices/administration/hudclips/handbooks/hsgh/4350.3 with it's Chapter 5 right now (https://www.hud.gov/sites/documents/43503C5HSGH.PDF) where income info starts on page 5-7).

**Comment by knod** [comment]
[Another option](https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=ccd82d677e91fcd79f0e53edf0456abf&mc=true&n=sp24.1.5.f&r=SUBPART&ty=HTML), though to find other parts, like definition for "elderly family" and medical care calculation details that aren't present there, but were present in other documentation may be elsewhere in 'Part 5'.

**Comment by knod** [comment]
Found the crossed out document with the way back machine. I provide this link with a caveat - it's possible the document was taken down because of inaccuracies it contained, so use with caution. Also, if anyone has ideas of how to check on that, feel free to comment. Way back:
https://web.archive.org/web/20170519042547/https://portal.hud.gov/hudportal/documents/huddoc?id=DOC_11749.pdf

[**Edit:** Currently, clicking on the link in Firefox takes you to the right document. Not in Chrome, though. Go figure.]

**Comment by WillMcIntosh** [comment]
The react-json-table package looks promising. We just need to put our data into json format to be rendered by react. (It's currently not, to my knowledge)

**Comment by lianilychee** [comment]
In issue description, updated mockup link to something more appropriate.

**Comment by knod** [comment]
Needs testing, which will be a different issue, and income exclusions, which is #207.
