### ISSUE TITLE
'Submit Feedback' and 'Reset' to 'Feedback' and 'New Client'

### ISSUE THREAD

**Issue by knod** [codeforboston/cliff-effects#468]
Change the text of those tabs on the side of the viewport, and nothing else!

- [x] Reset button changed
- [x] Feedback button changed

**Comment by Thescribe83** [comment]
Changed the 'Reset' text to 'New Client' also had to adjust some of the CSS, adding the extra size due to the lettering screwed it all up. I also added a hover element to it, so it is darker orange when hovering. I think it it better but obviously not needed.

**Comment by ethanbb** [comment]
Yeah, the way the CSS is now, the correct "top" and "left" values for the buttons depend on the size of the text they contain. It would probably be good to change it at some point so that's not true.

**Comment by knod** [comment]
I think we could put them both in a container and rotate the container instead. @Thescribe83: feel free to make a pull request!

**Comment by Leftere** [comment]
closed by #484

**Comment by knod** [comment]
My bad, not closed yet.
