### ISSUE TITLE
Mass Health benefit calculations

### ISSUE THREAD

**Issue by knod** [codeforboston/cliff-effects#47]
Current apparent breakdown from [this doc](http://www.mass.gov/eohhs/docs/masshealth/regulations/member-eligibility/130-cmr-505-000.pdf):
- [ ] Programs
  - [ ] Needed for MVP (don't currently know, but going to assume Standard is one)
       - [x] 505.002: MassHealth Standard
       - [ ] (130 CMR 505.003 Reserved) (doesn't appear in doc, may not count anymore)
       - [ ] 505.004: MassHealth CommonHealth
       - [ ] 505.005: MassHealth Family Assistance
       - [ ] 505.006: MassHealth Limited
       - [ ] 505.007: MassHealth Senior Buy-In and Buy-In
       - [ ] 505.008: MassHealth CarePlus
       - [ ] 505.009: MassHealth Small Business Employee Premium Assistance
  - [ ] Qualifications
       - [ ] Pseudo Code
            - [x] 505.002: MassHealth Standard
            - [ ] (130 CMR 505.003 Reserved) (doesn't appear in doc, may not count anymore)
            - [ ] 505.004: MassHealth CommonHealth
            - [ ] 505.005: MassHealth Family Assistance
            - [ ] 505.006: MassHealth Limited
            - [ ] 505.007: MassHealth Senior Buy-In and Buy-In
            - [ ] 505.008: MassHealth CarePlus
            - [ ] 505.009: MassHealth Small Business Employee Premium Assistance
       - [ ] Real Code
            - [ ] 505.002: MassHealth Standard
            - [ ] (130 CMR 505.003 Reserved) (doesn't appear in doc, may not count anymore)
            - [ ] 505.004: MassHealth CommonHealth
            - [ ] 505.005: MassHealth Family Assistance
            - [ ] 505.006: MassHealth Limited
            - [ ] 505.007: MassHealth Senior Buy-In and Buy-In
            - [ ] 505.008: MassHealth CarePlus
            - [ ] 505.009: MassHealth Small Business Employee Premium Assistance
  - [ ] Benefits for the same programs (currently we don't have a way to quantify benefits)
- [ ] Other data needed
  - [x] ~~Definition of a household~~ As per our client's input, for now we're assuming whatever household the user references will count as a household for all programs
  - [ ] Income calculations ([possible resource](http://www.mass.gov/eohhs/docs/masshealth/regulations/member-eligibility/130-cmr-506-000.pdf))

The current brainstorming doc I have going on (think this has too many details to work into a spreadsheet):
https://docs.google.com/document/d/1rVL9Wdr5GP_mYwQPuRXrRJOAPu4V3xcE7bFhI9KqYlI/edit#
It contains links to the above resources and more.

**Comment by lianilychee** [comment]
replaced by TAFDC
