### ISSUE TITLE
Test out updating to the newest version of React?

### ISSUE THREAD

**Issue by knod** [codeforboston/cliff-effects#472]
Could be an interesting project. I've certainly never tried it before. Would ideally involve going over the React change logs. We could split it up so that each person is reading a change log from a different version update.

**Comment by wacii** [comment]
[Strict mode](https://reactjs.org/docs/strict-mode.html) might help. It's a component that will print warnings when older features are used by its children.

React is still in v16 though, so there should be no problem in updating it.

**Comment by knod** [comment]
They say it should still be backwards compatible! But that's not always the case. Still, we could shut our eyes tight and take a leap.

For that matter, though, I'd like to update all our deps if we get a chance. Maybe I'll make a project for it ;)

**Comment by knod** [comment]
We can also definitely look into strict mode for future protection.
