### ISSUE TITLE
Fix 'Home' and 'About' links on the form pages

### ISSUE THREAD

**Issue by knod** [codeforboston/cliff-effects#473]
### Replicate:
1. From home page, click on 'Get Started'
2. Click on 'Home' or 'About' links in the top bar

### Result I'd Expect:
- Go to the 'Home' or 'About' page respectively

### Actual Result:
- Nothing happens

### Environment:
Operating system and version: OSX v10.11
Browser type and version: Chrome v65.0.3325.181
App version or commit id at the time: 9718ebd3aadd3b58ac9b66ebc6950ebd3e417757

### Other Notes
Would appreciate someone replicating and confirming this.

**Comment by knod** [comment]
Seems to stop working at commit 30254e18500967b1b2c8958225a4ed525d1de031

**Comment by ethanbb** [comment]
Confirmed on Windows 10, same Chrome version, same commit.

**Comment by ethanbb** [comment]
Observations:

* Works if you open in new tab
* Navigating directly to the pages in the address bar is also broken, but works if you try once, click in again and try again with the same URL.

Based on that it seems to be some problem with react-router...

**Comment by ethanbb** [comment]
Removing all node modules and package-lock.json and reinstalling doesn't help. Anyway, neither package-lock.json nor package.json has changed in dev since March. Either we must've changed something recently that somehow affected react router, or maybe it's related to an update to npm itself?

**Comment by ethanbb** [comment]
Oh, or this: https://github.com/npm/npm/issues/20328

**Comment by knod** [comment]
Works at commit bba65b8e452e155c69889f49ae0db9067826d752, but not at commit de03b3cf4aaac616b323b44957a6942858e10c47. Narrowing in.

**Comment by knod** [comment]
Works at baa5d2629228756aab4b0e4b4f962841e9aa4296 but not at 4fb0a32cfe0ba5c049c49ab0df063155fbe35d38 just after.

**Comment by knod** [comment]
It's pretty strange because I haven't seen the same thing changing between those times and I didn't `npm install` between any of them.

**Comment by wacii** [comment]
Pretty sure this isn't an npm thing. It works when the form has been interacted with. So it's just that when the prompt is hidden due to `isBlocking` React Router is not told to go ahead with the transition. Not sure when this happened. Maybe with my refactor.

**Comment by wacii** [comment]
Never mind. Was a little rushed before and didn't have time to properly read through the thread. Seems a bit more complicated than I had assumed. I'll spend some time with it.

**Comment by wacii** [comment]
All the mentioned commits were part of the feedback branch (I think). So I suppose we broke something then? The only meaningful difference I see is that we are not passing `isBlocking` to the React Router `<Prompt>` as `when`. But otherwise the issue is mostly what I suggested in my first comment.

I'll push the fix shortly.

**Comment by ethanbb** [comment]
OK, thanks for figuring this out @wacii! So I didn't notice the fact that it doesn't happen after you interact with the form. Could that explain the strange results from testing older results @knod, like why bba65b8 seemed to work? (Otherwise I can't think what it would've changed about this issue...)

**Comment by knod** [comment]
@ethanbb: I'm not sure. I didn't interact with the form at all any of those times, but maybe the code triggered something differently inside itself in those different branches, not sure. It didn't seem to happen randomly - it consistently worked for certain commits and not others, but randomness can happen that way sometimes.
