### ISSUE TITLE
Shall we start some github 'Projects' for our various goals?

### ISSUE THREAD

**Issue by knod** [codeforboston/cliff-effects#476]
In no particular order, the ones I remember are:
- [x] Linter and code style guide
- [x] Documentation
- [x] Conversational UX and Visual signals/style (ex: more clear visual signals about what step you're on)
- [x] Accessibility (the real deep down html-type stuff)
- [x] Component refactoring (maybe organize by functional vs. presentational?)
- [x] Style refactoring and consolidating style (CSS)
- [x] Testing (unit, regression, integration) (refactoring for testing)
- [x] Localization

Once you've added a project, remember to label already existing issues related to that project with the project's label.

**Comment by knod** [comment]
People seem cool about having these projects around, so I'm going to remove the 'discussion needed' label and maybe we can assign these to folks to start filling out.

**Comment by nicklee100** [comment]
I will take on accessibility. With the goal of how to make the app more accessibly.

**Comment by knod** [comment]
Some things I wanted to get down just so I don't forget.

Component general refactoring issues:
1. #167 
2. #264 
3. #405 

CSS Refactoring issues:
1. #286 
2. #287 
3. #288 

Testing issues:
1. #446

**Comment by wacii** [comment]
A style guide, huh? [Prettier](https://github.com/prettier/prettier) seems to be a pretty widely adopted approach nowadays...plus I really just want to mess up your carefully aligned variable declarations. I'm a terrible person.

**Comment by knod** [comment]
That you are. I'll take a look anyway :P
Also, we should make a github project in which to discuss this. Will ping the person who was into this when I remember their username. Sorry, person!

**Comment by knod** [comment]
Projects created and given 'urgency' and 'importance' scores. Would appreciate input on those scores and any thoughts about projects we're missing (e.g. refactoring other things, like utils, etc.).

**Comment by knod** [comment]
Folks seem to be ok with the 'labels' we have. We'll hold off on creating more projects until we have some more clearly defined ones.
