### ISSUE TITLE
Interested parties, vote on which code prettifiying settings to discuss more

### ISSUE THREAD

**Issue by knod** [codeforboston/cliff-effects#485]
A list of rules for prettifying-type-thing settings is presented. Mark items that you want to 'discuss'. Please just vote once. You get to put your name (or some kind of identifying mark), so if you make mistakes, I think there's a way to tell what happened. If not, we're humans, we can probably manage to figure it out.

To vote: http://pollmaker.vote/p/7YKGXI4S
To see results: http://pollmaker.vote/r/7YKGXI4S

A note while I'm thinking of it that may go in another issue:
**Pros of this linting/pretty stuff:** More consistent code! Huzzah!
**Cons:** More for a beginner to get up and running. Boo.
**Ideas:** Don't block PRs that aren't prettified. When someone who can do a drive-by reformatting passes near, they can make it better.

**Comment by wacii** [comment]
I didn't 100% get the inline comment item. But while I prefer comments before the code (narrower text is easier to scan), sometimes inline comments are useful. 

A number of the items listed won't work with Prettier. For instance, the library will format an object on one line or many depending on the allowed line length, which defaults to 80 characters. While you can change the line length, the other behavior cannot be changed.

If we don't want to use Prettier, I would still suggest using an established style guide. It's fine if you don't agree on every point, we can always make exceptions, but making a few exceptions is better than making dozens of decisions on the other style points that no one particularly cares about.

**Comment by knod** [comment]
Things I thought and never said:
Those things are good to know. I'm going to compile the agreements from our discussion into an issue and then it'd be great to have feedback on what's possible with Prettier, or, if better suited, another code formatter. If at all possible, I'd like to use one. Even I find it hard to keep to my own style guide.

That said, there will be some things that we can only do with a style guide, and we'll have to deal with that too.

Is it possible to have the formatter fix some kinds of white space (like indenting) while leaving other kinds of white space alone?

**Comment by knod** [comment]
Also, voting is closed for the poll and those items have been discussed! Huzzah! I'll set up another issue for setting out figuring out more details about what's possible.
