### ISSUE TITLE
Use eslint to fix code style issues (ongoing)

### ISSUE THREAD

**Issue by ethanbb** [codeforboston/cliff-effects#507]
We just added the linting tool eslint to make our code style more clear and consistent. Using the `--fix` option, it fixed many issues automatically, but several others (many relating to jsdoc comments) are still present. We should gradually fix these (while also avoiding introducing more issues in new features).

To use eslint to _view_ current style issues, do one of the following:
- Command line: with a branch derived from the current 'dev' branch checked out and all packages installed with `npm install`, run `npm run lint`. Warnings and errors for each file with issues should appear. Fix some issues, prioritizing errors.

- If you use Atom: install the package `linter-eslint` (including dependencies). Then issues and warnings should appear inline in each file when you have the project open.

- If you use VSCode: Install the package `vscode-eslint`. Click the install link on [this page](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint), which will open the extension in VSCode and allow you to install it there. Issues and warnings should appear inline in each file when you have the project open.

**Comment by knod** [comment]
I think for Sublime Text 3, you can use this package: https://github.com/SublimeLinter/SublimeLinter-eslint

**Comment by knod** [comment]
ESLint installation descriptions in our wiki now: https://github.com/codeforboston/cliff-effects/wiki/ESLint-Setup

**Comment by knod** [comment]
I think it'd be great if someone could edit in a more detailed description of using Atom's package manager.

**Comment by ethanbb** [comment]
Awesome @knod, just updated the Atom instructions.

**Comment by ethanbb** [comment]
Closing because @ethanstrominger has gotten rid of all the lint errors and warnings! Yay!
