### ISSUE TITLE
Bottom Label Change (Weekly Income -> Monthly Income -> Annual Income)

### ISSUE THREAD

**Issue by gerardotalora** [codeforboston/cliff-effects#511]
Suggestion:

The bottom label of the table only has the Annual Income option, this label needs to include the Weekly Income and Monthly Income as well.

**Comment by knod** [comment]
I've [pushed the changes](https://github.com/knod/cliff-effects-1/tree/graph-time), but I'll wait till linting PRs have been merged to avoid complex merge conflicts.
