### ISSUE TITLE
Convert hard-coded strings to keys for localization

### ISSUE THREAD

**Issue by ethanbb** [codeforboston/cliff-effects#513]
We want to factor out any and all strings in the interface into localization structures (like the one in `src/localization/en.js`) in order to let the whole app be translated into whatever languages we want/can. We also need to pass the `translate` function down to each display component so that it can retrieve the correct string(s) using a unique key.

See #489 for an example.

**Comment by knod** [comment]
Closed by #521

**Comment by knod** [comment]
@ethanbb: Isn't that covered by #500? I thought this was to change to a nested object instead of a flat one.

**Comment by ethanbb** [comment]
My impression was that #500 is to actually translate existing English strings into other languages, whereas this issue is to factor remaining string literals in the rest of the codebase out into the English localization file.

**Comment by knod** [comment]
Ah, ok. I'd been thinking of #500 for both, but maybe it's worth separating them.

**Comment by knod** [comment]
Maybe we could turn this into specific assignments - have an issue for each page that still need the localization infrastructure.

**Comment by knod** [comment]
@ethanstrominger , this was probably the issue you should have been referencing all along :/

**Comment by knod** [comment]
Just so we're clear, this is for purposes of localization.
