### ISSUE TITLE
make top left nav home to app; move CfB logo

### ISSUE THREAD

**Issue by ohmegasquared** [codeforboston/cliff-effects#542]
Common design patterns, noticed when an fellow member clicked it to try to go to the app home

**Comment by knod** [comment]
Great point! The CfB logo could go in the footer, for example. I think this should definitely be up for discussion!

**Comment by knod** [comment]
The group came to the conclusion that the right-hand footer would be a good spot for the logo. I think we have someone who's volunteered to give that a go. Will get them assigned as soon as we can.
