### ISSUE TITLE
Back button in browser behavior unexpected, `Forms` to pages/routes instead

### ISSUE THREAD

**Issue by ohmegasquared** [codeforboston/cliff-effects#545]

**Comment by knod** [comment]
What do you mean specifically? Can you fill out the regular issue template to explain more specifically? If you erased the existing one, you can find it again by starting to create a new issue and then just don't finish it.

**Comment by ohmegasquared** [comment]
Discussed with @shp54 & Ethan on Tuesday. If you have information in the tool and you try to use the back button, it throws away all data inputted and does not allow you to go back one screen. To duplicate: put in info one more than one page, then use the browser's back button. 

![back](https://user-images.githubusercontent.com/6669372/40849916-430d71a8-6591-11e8-9923-1a9d74e253e8.png)

**Comment by ethanbb** [comment]
@ohmegasquared: I don't believe it throws out all the data, unless there's a bug. The modal that pops up is supposed to guard against that and give the user a chance to go back to the form. On the other hand, it would be nice to have the back button work for navigating between recently visited form pages, until they reach the first one at which point we'd still have the same behavior that you currently see.

**Comment by ohmegasquared** [comment]
I think most users would expect the back button to navigate between pages.
I like the idea to keep the modal once they reach the first page!

Meghan Canale <http://www.linkedin.com/in/meghancanale>

**Comment by knod** [comment]
Ah, I understand the description now. Yeah, the form isn't many pages, just one. We can think about turning it into multiple pages. This was just the way it was originally set up and I didn't understand enough about `<Router>` then to change it. What level of urgency would you give this? A low level of urgency won't mean it gets deleted, just keeps it in perspective with the rest of the project.

**Comment by knod** [comment]
Just a quick note for whoever looks into this - remember that the client state still needs to be passed down to each page, so keep the router switching in 'VisitPage.js', not in 'App.js'.

**Comment by knod** [comment]
iirc folks agreed that this format would be best when we get a chance.

**Comment by knod** [comment]
Just so this issue is more searchable: We want to use Router to create a route for each form section so they become pages instead of just being sections.
