### ISSUE TITLE
Statement to users about SNAP calculation 

### ISSUE THREAD

**Issue by ohmegasquared** [codeforboston/cliff-effects#547]
When reading the user testing, it seemed SNAP calculation input was very important to users. Could we show the estimate of what SNAP calculation is? Could we consider a manual input to override if off? Wondering if there could be more than the written disclaimer.

**Comment by knod** [comment]
It was definitely a concern for the users. At the time of testing, though, we didn't have the disclaimer. I'll address the other questions in a bit, but I think it's worth considering that we haven't tested a version with the disclaimer, so we don't yet know if a different solution is needed.

> Could we show the estimate of what SNAP calculation is?

Can you give more details on what you mean? The estimate is shown at the end once all the data has been put in. Is the idea to display it somewhere else as well?

> Could we consider a manual input to override if off?

It's something we've discussed before. First, it may be better that an inaccurate result be visible and prompt them to send feedback about the inaccuracy. Our main concern, though, is that it would give a false impression that the tool was making accurate calculations. For my part, I'd rather they know the tool is wrong and approach the results with caution.

That said, if the disclaimer isn't enough, or if there's some better way to express the same idea, that would be great!

**Comment by knod** [comment]
During the most recent user testing, this didn't come up as a problem. We'll revisit it if it becomes an issue again.
