### ISSUE TITLE
Other circumstance change predictions besides income?

### ISSUE THREAD

**Issue by ohmegasquared** [codeforboston/cliff-effects#548]
Would more alimony cause, etc. cause a cliff effect? Should there be other inputs one can change on the prediction section? It could be an option to add field, and then chose from a drop down with other input they want to edit.

**Comment by knod** [comment]
That's definitely one of our wish-list items, and concrete wire frames about what that could look like would certainly be welcome.

**Comment by knod** [comment]
Because this would be such a big change and would take so much work to implement, I'm putting this on the wish list and removing it from current issues. Thank you for the brainstorming!
