### ISSUE TITLE
Usage of device sizes?

### ISSUE THREAD

**Issue by ohmegasquared** [codeforboston/cliff-effects#552]
What devices will be used most frequently? any phone usage? 

Asking as the site is optimized for large media, and not at all for small media

**Comment by knod** [comment]
For now, we've agreed with our partners that the MVP will assume Chrome on a desktop-sized screen. It's meant for case managers to use with their clients in the office at the moment. Does that make sense?

**Comment by rohitmusti** [comment]
I am not sure what the vision is moving forward for the project, but I know that mobile devices are more common that tradition computers in low-income communities.

**Comment by ethanbb** [comment]
@rohitmusti Hi Rohit! Thanks for stopping by. This could definitely be an important consideration going forward. For now, we're planning to deploy the app just to Project Hope case managers, who should be able to use Chrome on a desktop. But if it does end up being useful and accurate enough for public use eventually, we would want to do a mobile version.

**Comment by knod** [comment]
I think we'll table this for now and come back to it when we've reduced our queue and have some folks with those skills around.
