### ISSUE TITLE
Would text alert about a cliff coming up later be helpful for some users? To compliment the graphs 

### ISSUE THREAD

**Issue by ohmegasquared** [codeforboston/cliff-effects#554]
Would it be helpful for users to know where the “cliff effect” begins for certain benefits? Calling that out in *text* on the summary page?

**Comment by knod** [comment]
If I understand what you mean correctly, then what we'd have to do first is pinpoint a cliff. As people's income increases, their benefits will decrease. Where do we draw the line? Not all clients will run into a cliff. Maybe it's a discussion we can have with Kristin.

Personally, I'd like to set up a question that figures out what their total household out-of-pocket expenses are, and see if there's anywhere where the change in benefits takes their gross income under that line, or comes close to it. That's not the same as a cliff, but I think it would be a good thing for folks to know. I haven't yet had a chance to discuss with Kristin how best to implement that. See issue #397.

I also think it could be helpful if we could give more detailed information about the benefit changes written out in text as opposed to in a table or some other visual representation, but we haven't sat down to figure out what that would look like yet and it's not necessarily simple to construct. May be worth it, though.

**Comment by knod** [comment]
@ohmegasquared : Sorry about my completely unordered response before. I hope this one is more clear!

**Comment by snyderc** [comment]
I'm going to split the "more detailed information about the benefit changes written out in text as opposed to in a table or some other visual representation" into a separate issue and reference back to this one. I think the original meaning of this issue is to inform a user when they will experience a cliff effect, which is different than providing a text summary of the changes to benefits.

**Comment by knod** [comment]
I don't know why we didn't mark it as done, but it's done!
