### ISSUE TITLE
Custom benefit amount

### ISSUE THREAD

**Issue by knod** [codeforboston/cliff-effects#62]
It might be a good idea to let the client put in a custom benefit amount if they want so that if there are special circumstances around the benefit that we can't account for, there's a way for them to still get accurate results (some benefits can have an effect on the results of other benefits).

I'm not sure how it would translate to the chart at the end, but 1. there may be ways and 2. I think the benefit results are more important than the chart.

**Comment by lianilychee** [comment]
Would be good for recommendations, but not for MVP.
