### ISSUE TITLE
Entering 'rent' on 'previous expenses' raises an error

### ISSUE THREAD

**Issue by rst** [codeforboston/cliff-effects#64]
To reproduce:

 * Open the demo in a browser
 * Hit "intake new client"
 * Hit "submit"
 * Hit "create visit"
 * Hit "next" until on the "previous expenses" screen
 * Select monthly rent input field
 * Enter '10' 

Expected behavior:

 * Input should appear as typed, and be validated as appropriate

Actual behavior:

 * Screen is replaced with "TypeError: inputProps.id is undefined", with further backtraces

**Comment by rst** [comment]
FWIW, this is seen in Firefox 56 on Linux, and I see similar behavior when entering weekly rent.

**Comment by knod** [comment]
I think I've fixed this issue while fixing other problems. The PR is waiting for review. In the meantime, @rst was asking about format of bug reporting. I think we need to add a part that includes a description the environment in which the bug was observed.
