### ISSUE TITLE
Deploy preview for PRs

### ISSUE THREAD

**Issue by zhujinxuan** [codeforboston/cliff-effects#657]
**Do you want to request a feature or report a bug?**
feature

**What's the expected behavior?**
After submitting a PR, a bot shall deploy the site in a PR-specific url for previewing the changes made by PR.

Recently I submit a PR in slateJS. I find that they are using netlify.com; So each time after submitting a commit, then it will use netlify.com to deploy a example-site based on that PR (like https://github.com/ant-design/ant-design/pull/11189#issuecomment-402970977). When new commits comes to the PR, the deployed example will be automatically updated.

Then we can easily understand that changes made by the PR by viewing the provided deploy preview.

**Comment by zhujinxuan** [comment]
The deploy preview is very easy to set.  Just go the netifly.com, tell 
1. which repo want to deploy preview
2. which cmd is used to generate deploy
3. the directory path (`build/` in this project) to store index.html for deploy.

**Comment by knod** [comment]
If you feel up for setting it up, I say go for it! It sounds like a great tool :)

**Comment by zhujinxuan** [comment]
@knod Hi, I need to be a member of codeforboston organization to set-up netifly

As the image below, I need to grant permission as an organization member.

<img width="860" alt="screen shot 2018-07-13 at 11 03 02 am" src="https://user-images.githubusercontent.com/746159/42698617-6abf498a-868c-11e8-855a-b70119a46c6b.png">

**Comment by knod** [comment]
Shoot! Didn't realize no one had added you yet. Will do now.

**Comment by knod** [comment]
Ah, sorry, I didn't quite understand the requirement. We'll have to talk to the core team at CfB to see how they think this can work.
