### ISSUE TITLE
Avoiding Travis cache issues - options

### ISSUE THREAD

**Issue by knod** [codeforboston/cliff-effects#667]
The Travis folks got back to me about avoiding this in the future. We can either to get rid of cache in the config or, when we edit something related to Travis, we manually go to https://travis-ci.org/codeforboston/cliff-effects/caches and delete our current cache archives.

The first would be automatic, which is a plus, but which would probably mean a longer wait time for the tests to run. The second is more knowledge that would have to be spread around, but the tests would probably be faster. Unsurprisingly to the folks who know me, I'm in favor of the first option - getting rid of the cache entirely. We could probably get rid of the comment I added at that point, and not have to add a new comment about caches!

Thoughts?

**Comment by Butterwell** [comment]
Group decision: remove cache.
