### ISSUE TITLE
Remove minor version numbers from google localization docs

### ISSUE THREAD

**Issue by knod** [codeforboston/cliff-effects#668]
I'll be sad to lose my security blanket, but it'll simplify using version numbers a bunch. When you remove the minor version number, remove the quotes around the key as well.

Start off with
- [x] en.js

Then move on to
- [x] bn.js
- [x] de.js
- [x] es.js
- [x] fr.js
- [x] pt.js
- [x] zh.js

More specifically, right now the format of keys is `name_v#.#`, but we want it to be `name_v#`. So we'd want `name_v1.0` to turn into `name_v1`.

**Comment by knod** [comment]
Files are at https://drive.google.com/drive/folders/1QDCwxmTWZ8-9nLUg_b0M47UYaHXFR3n0.

**Comment by knod** [comment]
Start off with

**Comment by knod** [comment]
@pporfilio : This issue is specifically for the google docs. The repo files also need version numbers, but that'll require changes to the way they're called in the code as well. There was supposed to be an issue for that, but I can't find it, so it must have all been a dream. Feel free to make it if you get the chance!

**Comment by pporfilio** [comment]
I've updated the google docs so that they no longer have minor version numbers. I'm closing this issue since there isn't a corresponding PR.
