### ISSUE TITLE
How shall we handle different types of NaNs passed to math functions

### ISSUE THREAD

**Issue by knod** [codeforboston/cliff-effects#67]
Should we give different feedback for `null`, `undefined`, and `NaN`? If so, what kind? Should they cause different errors? See some discussion in #63.

**Comment by yhou8** [comment]
If people are comfortable with static typing we could consider adding [Flow](https://flow.org/) to the workflow. It's an optional Javascript type checker that works well with React and allows you to add type checks to select functions. We can use it to create functions that reject null and undefined inputs. NaN are treated as legitimate numbers, but if we can limit the possibility of undefined to NaN conversion it shouldn't be a problem. Flow can also check for other issues. It requires a processing step before deploying, but we could add it to the npm deploy script.

**Comment by knod** [comment]
Possibly continue broader discussion in #95
