### ISSUE TITLE
Add all user-visible strings to localization files and access them via the snippets mechanism

### ISSUE THREAD

**Issue by pporfilio** [codeforboston/cliff-effects#676]
Currently there are a lot of strings that will be visible to users throughout the source code. We need to pull these out into localization files and replace the strings with interpolated strings that are generated by the interpolateSnippets function.

For example, Predictions.js needs to have its strings extracted and converted to be more like AboutContent.js, which already uses the snippet system.

**Comment by ethanbb** [comment]
Hey, I believe this is actually a duplicate of issue #513. No worries though, it's an old issue that's hard to find at this point - we've been working on it for a while!

**Comment by pporfilio** [comment]
Oh man, that was even assigned to me : / Not sure how I missed it. Sorry about that.
