### ISSUE TITLE
Week/Month/Year graphs warp (move) on change of axis

### ISSUE THREAD

**Issue by Butterwell** [codeforboston/cliff-effects#689]
### Replicate:
1. On "Stacked Incomes" press "Weekly"
2. On "Stacked Incomes" press "Yearly"
3. On "Stacked Incomes" press "Monthly"

### Result I'd Expect:
The graph line not to move 

### Actual Result:
The graph line moves

### Environment:
Operating system and version: 
Browser type and version: 

App version or commit id at the time:

**Comment by knod** [comment]
Good point, though not something we've figured out how to fix with chart.js. Is your plate clear and is this something you'd be willing to take on?

**Comment by Butterwell** [comment]
Sure. I'll take this on.

**Comment by knod** [comment]
We'd like to look into a new chart lib to see if we can get something that has more capabilities that we're looking for.

**Comment by knod** [comment]
With some math and the new chart lib, we're all set on this! Huzzah!
