### ISSUE TITLE
Remove version property from the localization google docs and update the script accordingly

### ISSUE THREAD

**Issue by pporfilio** [codeforboston/cliff-effects#712]
Localization files: https://drive.google.com/drive/folders/1QDCwxmTWZ8-9nLUg_b0M47UYaHXFR3n0

**Comment by knod** [comment]
Done. Also, updated the scripts to show missing properties at the top, though the way it does it is a bit opaque, but necessary to avoid having to parse the document completely. Someday we may write up an attempt at a clear description...
