### ISSUE TITLE
Edit footer 'Cliff Effects Tool' to link to github repo

### ISSUE THREAD

**Issue by knod** [codeforboston/cliff-effects#725]
I was originally thinking of this as a task for a new coder, but considering it'll involve the interpolating, it may be more complex than that. What do folks think? Will it be straightforward enough to assign it to someone new?

**Comment by ethanbb** [comment]
I think someone at least somewhat familiar with the interpolation mechanism but who maybe hasn't actually used it yet could try to figure this out.

**Comment by knod** [comment]
Makes sense. Not a 'beginner friendly' issue, then.

**Comment by jlangevin** [comment]
Not sure if beginner friendly meant programmer or new to project.  Perhaps ignorance is bliss?  I'm new to CfB so figured I'd take a stab at this after spending some time looking through the code today.  I just submitted a pull request.  Hope that's not a problem.

**Comment by knod** [comment]
@jlangevin : Not a problem at all! Thanks a ton! 'Beginner friendly' currently means both. I think it's meant to hook into github in some way. I think there are two options for the github hook, though, so maybe we could use each to mean a specific thing. Worth discussing!
