### ISSUE TITLE
Change wording on the "Child Support" section of the "Expenses" page

### ISSUE THREAD

**Issue by pporfilio** [codeforboston/cliff-effects#762]
In the 9/13/18 user test, there was confusion that this section was asking for child support related income (as opposed to expense).

Change the text to state that the child support is "paid to someone else" or "paid out".

https://docs.google.com/document/d/1Np8AvGmkKA7g6fSc51CauY-aj4SZ_E286MrJNK9qqa0/edit#

**Comment by knod** [comment]
Or, as suggested by @ethanbb - 'Child support you pay'.

**Comment by knod** [comment]
Takes over and closes #723

**Comment by knod** [comment]
This has been re-opened by the reversion.

**Comment by knod** [comment]
New suggestion - 'Child support you are legally required to pay'
