### ISSUE TITLE
Add a text description of the results table

### ISSUE THREAD

**Issue by pporfilio** [codeforboston/cliff-effects#763]
In the 9/13/18 user test, the Changes table on the Predictions page was confusing. We want to have a paragraph that summarizes the results that are currently presented in that table.

https://docs.google.com/document/d/1Np8AvGmkKA7g6fSc51CauY-aj4SZ_E286MrJNK9qqa0/edit#

**Comment by knod** [comment]
@2001zhaozhao : I've got a demo going for this right now, but it'd be awesome for us both to develop it separately and see what we each come up with. If you don't want to do that, that's ok as well. Let me know!

**Comment by knod** [comment]
Also, my bad for not mentioning that in this issue.

**Comment by knod** [comment]
This was previously #687, but I'm closing that one down. @2001zhaozhao , you may want to take a look at that one.
