### ISSUE TITLE
Add suggested search terms on the Predictions page to help users find resources to deal with cliff effects

### ISSUE THREAD

**Issue by pporfilio** [codeforboston/cliff-effects#764]
If a user finds out from our tool that they are going to run into a cliff effect, they are left with bad news and no next steps.

We're concerned about linking to a specific web page because that resource could go out of date. But if we could recommend some search terms to start with, it might encourage users to seek out additional help for themselves without someone needing to maintain links to resources.

- [ ] Find some resources related to managing cliff effects
- [ ] Identify search terms that lead to these resources
- [ ] Add text to the predictions page suggesting that users try these search terms to find more information

https://docs.google.com/document/d/1Np8AvGmkKA7g6fSc51CauY-aj4SZ_E286MrJNK9qqa0/

**Comment by knod** [comment]
We also mentioned that this would just show up when a cliff occurred, but maybe it should always be shown. I mean, when would that information ever not be useful?

**Comment by knod** [comment]
Also, I've put out feelers to Kristin about this.

**Comment by knod** [comment]
Kristin just said that there weren't any really useful search terms and to search for social services in your area was your best bet :/

**Comment by knod** [comment]
When I tried to search it was pretty fruitless.
