### ISSUE TITLE
Button colors don't change on keyboard focus

### ISSUE THREAD

**Issue by knod** [codeforboston/cliff-effects#842]
### Replicate:
1. Use keyboard navigation to tab to neutral-colored buttons

### Result I'd Expect:
- Either the buttons would look like they were being hovered over or the buttons would look like they've been selected.

### Actual Result:
- No change in style

### Environment:
App version or commit id at the time: a83dc1d1ffff664ed2b4d55020bd7a3d0bc6e965

### Other Notes
Needed for:
- [ ] Home page (knod)
- [ ] Main nav bar
- [ ] Form bottom row buttons
- [ ] Form left-side buttons
- [ ] New-household-member creation UI
- [ ] Results tabs?

**Comment by 2001zhaozhao** [comment]
Microsoft Edge seems to add a very visible edge to selected elements, both when tab-selecting and when navigating with a mouse.
![capture](https://user-images.githubusercontent.com/15002454/46706255-87317880-cc01-11e8-94a8-2a069bb7a6c3.JPG)

Another note: the orange "New Client" button on the left still does not have a tab-focus color. Also, focusing on textboxes and checkboxes is barely visible. Maybe enlarge the border when focused?

**Comment by 2001zhaozhao** [comment]
It seems like focus highlighting is largely a browser thing.
Here's how selecting a Github button with TAB looks like in Chrome:
![capture](https://user-images.githubusercontent.com/15002454/46707099-661f5680-cc06-11e8-8358-fc706e64ed12.JPG)
Here's the same button in Edge:
![capture2](https://user-images.githubusercontent.com/15002454/46707111-759e9f80-cc06-11e8-8c42-9d379d7af2ac.JPG)

**Comment by knod** [comment]
@2001zhaozhao - Some followup questions:
> Microsoft Edge seems to add a very visible border to selected elements, both when tab-selecting and when navigating with a mouse. This does not happen in Chrome.

If it's showing up in Edge, it should be showing up in Chrome. Have you tried opening a private window in Chrome and looking at the dev version? Sometimes I can't get Chrome to properly delete cache and the new changes don't show themselves.

> the orange "New Client" button on the left still does not have a tab-focus color.

Do you mean it doesn't get a focus outline? If so, that's very strange because my version on 'dev' does.

> Also, focusing on textboxes and checkboxes is barely visible. Maybe enlarge the border when focused?

What shows up for me is a single line border instead of a double line border. Is that what you see?

**Comment by knod** [comment]
We never heard back about this, so we'll have to close this one down for now.
