### ISSUE TITLE
Fix result text summary has duplicate keys in React

### ISSUE THREAD

**Issue by knod** [codeforboston/cliff-effects#851]
### Replicate:
1. Create a cliff
2. Go to the Predictions page

### Result I'd Expect:
- No errors in the console

### Actual Result:
- Errors in the console about duplicate keys in an array of elements. Doesn't break the page, but still not ideal. Example: 'Encountered two children with the same key, `en236`'

### Environment:
App version or commit id at the time: 943b9fd4a8cdc8d24637ed89ad4666db04af7a52

### Other Notes
It might the benefit program loop. The key named in the error is a snippet-like key.

**Comment by 2001zhaozhao** [comment]
Seems like getting rid of the JSX constructs and opting for a more traditional string joining method gets rid of the error. 
For now, I couldn't get everything to work using string joining (the snippet strings were all displaying as [object Object]), so maybe I'll get back to this later, or someone else can work on it.

**Comment by knod** [comment]
The keys for the snippets are created when the snippets are interpolated. So the `i_period` snippet has the same key, no matter where you put it. So if it appears in one array multiple times, that could be a problem. I'm not sure of a way around this. Possibly wrapping those individual items in another span with a unique key? Having each snippet be a class with a getter that creates the unique key on the spot? That hides implementation a lot, which isn't great.

Anyway, maybe tracking down the problem first would probably be more productive than speculating more right now. Maybe it's a really simple fix.

**Comment by dylanesque** [comment]
Do we know for certain what line number/component this emanates from?

**Comment by knod** [comment]
From what I've examined, everywhere `i_period' and 'i_beforeMoney' are used multiple times in the same paragraph are the problem. This was my fix for the conference:
```js
var detailsNow = (
  <p>
    <span>{sn.i_nowEarn} {sn.i_beforeMoney}{toMoneyStr(current.earned)} {sn.i_eachTimeInterval}</span>
    <span>{` `} {sn.i_nowBenefitsTotalIs} {sn.i_beforeMoney}{round$(current.benefitsTotal)}{sn.i_period}</span>
    <span>{` `} {sn.i_nowTotalIs} {sn.i_beforeMoney}{round$(current.total)} {sn.i_eachTimeInterval}{sn.i_period}</span>
  </p>
);
```
