### ISSUE TITLE
Improve Color Contrast on Selected Site Elements

### ISSUE THREAD

**Issue by dylanesque** [codeforboston/cliff-effects#852]
More contrast needed for hover and other interactions, including:
 - [x] General nav bar
- [x] Form section nav bar
- [x] Spouse vs. other member drop down in 'Household' form section

**Comment by 2001zhaozhao** [comment]
For the general nav bar we can darken the entire text area on hover.

For the form section nav bar we can darken non-selected items more on hover, making it darker than the currently selected one. We might also change the text color of the currently selected item so that it is dark green and stands out more from the black color of the other items.

For the family member dropdown menu, the currently selected item could also be darkened when hovered over (currently it does not).

**Comment by dylanesque** [comment]
> For the general nav bar we can darken the entire text area on hover.
> 
> For the form section nav bar we can darken non-selected items more on hover, making it darker than the currently selected one. We might also change the text color of the currently selected item so that it is dark green and stands out more from the black color of the other items.
> 
> For the family member dropdown menu, the currently selected item could also be darkened when hovered over (currently it does not).

Those are definitely good suggestions, I'll get started with these tomorrow.

**Comment by dylanesque** [comment]
An update, since this is moving slowly. I'm having trouble finding where to modify the active state needed to tweak the styles on the second item on this list. I was able to find the component it emanates from, but not the code that modifies it, which leads me to believe it's a semantic-ui-react thing. I'll have to dig through those docs.

**Comment by knod** [comment]
@dylanesque : What I do is examine selectors in the inspector and use those in the css file. There's a way to trigger the hover state in that interface so you can see those styles working.

**Comment by dylanesque** [comment]
I can swing that. I might have to use !important or some other hacky technique, which I don't love, but it feel like the only options sometimes.

**Comment by knod** [comment]
If we run across the need for !important, we can discuss our options.

**Comment by dylanesque** [comment]
Figured out the targetting problem, will need more time to figure out a solution that doesn't involve !important. For my own reference, the color to slot in is #dcddde

**Comment by dylanesque** [comment]
Closing this issue because of the requested changes are in place, and just the the specific colors signed off on.

**Comment by knod** [comment]
Sorry, our bad if there was miscommunication. We wait till PRs are merged before closing issues, partly because of the nature of this volunteer work.

**Comment by knod** [comment]
You can close it in your PR title though, as described in https://github.com/codeforboston/cliff-effects/wiki/Guide:-PR-Excellence!
