### ISSUE TITLE
Change references to organizations

### ISSUE THREAD

**Issue by knod** [codeforboston/cliff-effects#875]
Shoot folks, we need to change references of CSP and Project Hope from partners to former partners/whatever - in the README, the announcement, and the About page. May need to think about wording for this.

- [x] README
- [x] About page (knod)
- [x] CfB announcement wiki page [_Note: 2 pages now exist. One for jumper, one for instigator._]

**Comment by knod** [comment]
Shoot, and the announcement slide too. Hmm, there's a way for one of us to change that...
- [x] CfB announcement slide

**Comment by knod** [comment]
- [x] Aaaaand the CfB webpage 😝 (knod in progress)

Why are those different things?

**Comment by dylanesque** [comment]
Something like this? Do we need to erase references to Project Hope entirely?

"We are building the Cliff Effects webapp to help* Project Hope case managers make quantifiable predictions about their clients' potential cliff effects - and advise their clients accordingly." --> "The Cliff effects webapp was originally conceived as a tool to help* Project Hope case managers make quantifiable predictions about their clients' potential cliff effects - and advise their clients accordingly."

**Comment by knod** [comment]
Exactly - we want to switch from referring to them as current partners to referring to them as previous partners, etc. We may want to work on 'plain language' a bit more.

**Comment by knod** [comment]
@dylanesque : It'd be great to have your notes from the readme (about page?) PR in here too.

**Comment by knod** [comment]
Finished through a series of PRs that failed to reference this issue.
