### ISSUE TITLE
Allow chart to show income by other timeframes

### ISSUE THREAD

**Issue by knod** [codeforboston/cliff-effects#89]
(Not for MVP) Right now the result chart/graph's ticks are annual income amounts. Considering clients will probably be putting in weekly amounts, presumably because they're more familiar with them, it might be more useful to the client if we initially show the tick mark values as weekly amounts. We can probably find a way to allow the user to switch to monthly or yearly amounts too.

**Comment by lianilychee** [comment]
Will be part of design recommendations, but as you noted, not for MVP.

**Comment by knod** [comment]
I may work on this for now, since Kristin said it may be a bit of an issue. Will re-close if needed.

**Comment by knod** [comment]
Currently this commit on my repo shows a version: 0a1bc40c581bd0d91c1f5bbe5a05e3b042c63940
My repo: https://github.com/knod/cliff-effects-1
My repo branch (may be deleted in future): https://github.com/knod/cliff-effects-1/tree/graph-time
