### ISSUE TITLE
Convert var to const/let

### ISSUE THREAD

**Issue by turnerhayes** [codeforboston/cliff-effects#899]
var has some weird behaviors (hoisting to top of the function, function-scoped rather than block-scoped) that `const` and `let` avoid. Eslint has a [rule](https://eslint.org/docs/rules/no-var) to enable this, and can auto-fix it.

**Comment by knod** [comment]
Just so the question is out there in the world - is discussion needed on this? I'm not sure why there'd be objections, I just know we've had other discussions about linting choices.

Personally, I think it can just go ahead. Maybe just a head's up on Slack.
