### ISSUE TITLE
Pass necessary props through BigButton

### ISSUE THREAD

**Issue by turnerhayes** [codeforboston/cliff-effects#914]
As mentioned in [this comment](https://github.com/codeforboston/cliff-effects/pull/894/files#r228693203), `BigButton` needs to pass more props through to its underlying button (`onClick` at least).

**Comment by turnerhayes** [comment]
FWIW, the way I've seen most libraries handle things like wrapped inputs is to pass any props that it doesn't directly use itself down to the underlying input (the way it was before); see, for example, [Material UI](https://material-ui.com/api/button-base/). That doesn't necessarily mean it's right, but it does seem to be the way a lot of people have resolved it in React world. I'm inclined to go that way; there are a lot of props that could be used by consumers that we don't want to have to list out (e.g. `onFocus`, `onBlur`, `onMouseEnter`, `form` etc.).

What gives you pause about passing arbitrary props down?

**Comment by knod** [comment]
Part of the question is about how to pass the props down in a way that's extensible so we can pass down stuff without worrying about accounting for every single possible prop in the code of `<BigButton>`. One way goes something like this:
```js
const BigButton = function ({ children, specificProp, ...buttonProps }) {
  return (<Button someProp = { specificProp } { ...buttonProps } >{ children }</Button>);
}

<BigButton
  specificProp = {true}
  onClick      = {function () {}}
  onFocus      = {function () {}}>
  Text
</BigButton>
```
That way's a bit dangerous, but that's the most flexible and easiest to write for. We can pass down things like `color` and `disabled` as if we were just handing it down to `<Button>`. Another way does something more like this:

```js
const BigButton = function ({ children, specificProp, overrides }) {
  return (<Button someProp = { specificProp } { ...overrides } >{ children }</Button>);
}

<BigButton
  specificProp = {true}
  overrides    = {
    onClick: function () {},
    onFocus: function () {},
  }>
  Text
</BigButton>
```

That's safer, but more painful. Maybe there are other ways to handle it too.

Discuss!

**Comment by knod** [comment]
Those last two comments would probably work better switched, lol. My hesitancy in passing down props is getting unintended props in there by accident which would be hard to trace, but I'm not married to any particular method.

**Comment by turnerhayes** [comment]
The way I see it, `BigButton` is basically a standin for `Button`; it's not its responsibility to gate props any more than it's `Button`'s. It seems like `BigButton` should have essentially the same API as `Button` since it's not really doing anything other than setting some defaults.

**Comment by knod** [comment]
Fair point!
