### ISSUE TITLE
package-lock.json with npm

### ISSUE THREAD

**Issue by knod** [codeforboston/cliff-effects#929]
Removing all the carats didn't do it. How do we deal with this?

**Comment by dylanesque** [comment]
Not sure I cross-posted the thread from Boston JS I started about Yarn/package-lock.json issues, but doing that now. Bullish on Yarn being our solution for the headache of keeping everybody's ~~npm~~ Yarn version in sync, but I seem to remember other helpful suggestions in there.

**Comment by dylanesque** [comment]
One possibility is ```npm ci```: https://docs.npmjs.com/cli/ci

**Comment by knod** [comment]
Below is the thread from Boston JS. From what I can tell, it says yarn seem like it probably works for the p-l issue if you've got a lockfile, but
   1. It requires the whole team to have the same yarn version
   1. It's hard to make sure new members aren't using npm instead (though `.gitignore`ing the p-l helps)
   1. Some editor plugins assume you're using npm so they'll freak out if you're using yarn

For npm, removing carats is supposed to work, but we've tried that and it hasn't solved the issue.

Have I missed anything crucial?

09/14/18
Person1
I just got involved with an open-source project, and learned about this ongoing bug with package-lock.json files in npm where they defer to the package.json files and dont' stay, um, locked. Is anybody using Yarn instead of npm? I've used it and it seems fine, but are there any major drawbacks or gotchas in Yarn vs npm?

Person2
I've used yarn pretty much since it came out, it works for me.  The greatest complement I can give it is that I can't remember the last time I have had to delete node_modules and reinstall to get things working again.

Person3
that sounds too good to be true

Person4
Yeah, I can echo what Person2 said
I've been using yarn for about 1.5 years
same

Person2
if there is a drawback, I would say that because it an external dependency that you need to make sure everyone keeps it up to date

Person4
Interestingly, I've seen some people get around that by having a versioned copy of yarn in their repo
that way you can do utils/yarn.js [command]

Person2
hmm thats a good idea

Person4
sorta hacky and it bloats the repo but it works!

Person5
wouldn't yarn behave the same? the `package.json` is still the source of truth no? I know that yarn has a `--frozen-lockfile` option you can pass that will cause the install to fail if it detects a change to the lockfile.

	Person1
	I did not know this, and glancing at the npm docs, they don't seem to have an equivalent feature

	Person5
	yeah it's odd, I see that there have been some proposals to add it. I think if you want to have truly static packages you need to use the `-E` flag on install to resolve a fixed version.  alternatively you can modify the `package.json` to remove the leading `~` or `^` from a package (edited)

	moss [33 minutes ago]
	Actually, that seemed not to work for us. We did that and then got the same problem from a couple people - a different pl file.

	moss [33 minutes ago]
	Have you done this in a way that worked for a whole team?

Person5
I know npm added the `npm ci` command for build pipelines which does the same, but also dumps the `node_modules` folder and does a fresh install.

Person2
hmm, I think that may be true, the package.json is still the source to truth unless you use --frozen-lockfile

Person6
yarn does have its share of bugs, and their lock file is only deterministic for a given version of yarn, so you have to make sure everyone's on the same version (that's not true to the same extent in npm), but we're pretty happy with yarn here (early adopter, started using it  pretty much the week it came out, here).
The biggest thing I see as a drawback is if you use yarn specific features and are in a big enough team, there's always the occasional person who uses npm instead and wonder why stuff isn't working... or tools that make some assumptions about npm (eg: vsce when building VSCode extension, it supports yarn too, but I haven't been able to make that work properly)

Person5
I'm interested to see how Yarn Plug'n'Play turns out. they're looking to get rid of `node_modules` and are showing up to 70% faster install times.
https://github.com/yarnpkg/rfcs/pull/101

Person6
We're looking at that pretty closely too, though not so much for the implementation, and moreso because of the effect on the ecosystem.

The biggest issue with doing anything about node module resolution is the entire ecosystem makes assumptions about node_modules, and these effort shakes those assumptions and force tools to provide better hooks (or document hooks) to change it.
at HubSpot we already do something fairly similar to the PnP stuff, but we have to fight with every editor and every tool that comes out to make it play nice with our resolver.

Person7
I got fed up with `package-lock.json` so I got in the habit of adding an `.npmrc` file to my repos, with the following lines:
```
package-lock=false
save-prefix=''
```
This basically says, don't use a lockfile, and don't save the `^` carets to my `package.json`. Just save exactly the version that I specify. Not sure if there are any downfalls to this approach, but I haven't really run into any yet.

	Person6
	the problem with that is that transitive dependency versions will still change automatically if you don't have a lock file.

**Comment by knod** [comment]
@pporfilio found this post that seemed to solve the issue for him: https://stackoverflow.com/questions/47638381/why-did-package-lock-json-change-the-integrity-hash-from-sha1-to-sha512. It's unclear if all the commands have to be run every time, or if the npm updating can just be run once. It's also unclear whether you do really have to install a global version of npm or whether a node version manager like `nvm` or `n` would work just as well.

There's also some indication that it might not always work, especially with a team where people have both macs and pcs: https://stackoverflow.com/a/48922618.

This team seems to have switched to yarn and has a bunch of details, though it involved some stuff I'm not sure we need: https://github.com/akeneo/pim-community-dev/pull/6574. Haven't yet asked if they've encountered any issues with yarn.

**Comment by knod** [comment]
The folks at npm seem to have felt that at least one incarnation of this issue was solved last December: https://github.com/npm/npm/issues/17749#issuecomment-352307006. If people have trouble, they want a new issue that has something that can be reproduced (that's at the bottom of the thread).

**Comment by knod** [comment]
We could also use this lib to just have a post-install hook: https://github.com/typicode/pinst. It would do `git checkout .`. A couple problems I can see:
1. It'd unexpectedly get rid of someone's changes if they forgot to stash or commit them. A possible solution is something like `git stash && git checkout . && git stash pop`, but I don't know how to make the stash pop conditional on something having been stashed. Otherwise it'd lead to unexpected stash popping...
1. It'd be nice if there were a way to disable it for when we really do want to update the p-l.

Or maybe we delete the p-l and then just `.gitignore` it? Would that create other issues?

**Comment by knod** [comment]
We could also create an .npmrc file and put the line `package-lock=false` in there. Hmm, that may be the best solution if it doesn't cause other issues.

**Comment by knod** [comment]
So, it looks like getting rid of p-l can cause its own issues: https://github.com/npm/npm/issues/17722#issue-242057316

Namely, depending on your OS, your `npm install` can get rid of or add certain packages automatically. If we end up using one of those packages, it'd be pretty annoying - every time a person with a different OS was installing, they'd end up making a PR with a different version of package.json. Which would basically be the same problem, though the size of the file change would be smaller than with the p-l problem.

**Comment by knod** [comment]
Maybe we can use the pinst package and somehow also add an npm script that bypassed it when we wanted to update the p-l? It looks like we might be able do it with something like:
```
// package.json
scripts {
  "postinstall": "git checkout .",
  "install-pl": "pinst --disable && npm install && pints --enable"
}
```
I'm not sure if that would do the trick or if it would need tweaking. From the docs: https://github.com/typicode/pinst#usage

**Comment by knod** [comment]
That would still leave us with the unexpected removal of changes behavior, though. Can we write a script to create a dialogue for the user that would ask them if they'd stored changes and then let them cancel the command if they need to? There must be a way.

**Comment by knod** [comment]
In #977, Travis had issues because the package.json and the p-l.json were not in sync with each other. That needs to be kept in mind as we move forward.

**Comment by knod** [comment]
We currently don't have a solution for this, so I'm closing it. We've had fewer problems with fewer carets and hopefully that will be enough.
