### ISSUE TITLE
.langCode incorrectly displaying in each section or localization report

### ISSUE THREAD

**Issue by jlangevin** [codeforboston/cliff-effects#947]
Report contains an entry like the following:
"aboutPage.langCode should exist."

`.langCode` exists as a key at the top of the localization object only.  It's being treated as if it's a key in every object.

**Comment by knod** [comment]
It actually _is_ passed down to every object, it just isn't a snippet, it's meta-data, and doesn't need to be in the localization report.

**Comment by jlangevin** [comment]
See PR #949 for a solution that allows coexistence of functionality without having to change the localization object mutation in interpolateSnippets().
