### ISSUE TITLE
Type checking

### ISSUE THREAD

**Issue by knod** [codeforboston/cliff-effects#95]
Should we or shouldn't we type check? Implicitly or explicitly? If we type check, what shall we use to do that? For example, Flow can do implicit or explicit type checking.

**Comment by yhou8** [comment]
Flow seems to be more popular for working with React than Typescript. One scheme for where to use explicit vs implicit types is to annotate function arguments and return values while relying on type inference for internal variables. That allows you to document what a function does, especially whether it handles null/undefined, while allowing more freedom in implementing a function. Annotating the types of object member variables would also be useful.

**Comment by knod** [comment]
To put in my $0.02, type checking could be a very useful thing, especially for field inputs and when sending and/or objects to/for calculations. I also think it might be not be a problem to put it on hold until after the MVP is done.

**Comment by shp54** [comment]
I agree that type checking is a larger concern that can wait until after the MVP is done.

**Comment by knod** [comment]
Decided then. No type checking, though we are going to make sure client object always has valid values, as discussed in #166.
