### ISSUE TITLE
New chart library/new charts

### ISSUE THREAD

**Issue by knod** [codeforboston/cliff-effects#956]
So far two have been suggested:
1. Highcharts with a non-commercial license: https://shop.highsoft.com/faq#Non-Commercial-0
2. Chartist.js https://gionkunz.github.io/chartist-js/index.html

Highcharts looks pretty swank and quite worth checking out, imo (thanks @turnerhayes)

- [x] Line graph
- [x] Stacked area graph
- [x] Bar chart

Wanted:
1. Zooming/panning (chartjs doesn't).
2. Overlaying multiple types of charts on each other (chartjs does).
3. Ability to stay the same size even when labels text increases in length, like when switching between weekly, monthly, and yearly amounts (chartjs doesn't).
4. Accessibility would be awesome (chartjs probably doesn't).
5. Also printing, though that might be a bit messy depending on if we want to be able to have an option to print multiple result types (chartjs probably doesn't manage that itself).

**Comment by knod** [comment]
For Highcharts, I've found:
1. https://github.com/whawker/react-jsx-highcharts
2. https://github.com/kirjs/react-highcharts

**Comment by knod** [comment]
[Using react-jsx-highcharts]

~So far, one issue with highcharts is its width is annoying. It only takes pixel or percent values. A percent value would mean us really digging deep to make sure there's a solid width property for the chart's parent container. A pixel value means less responsiveness. We can add some responsiveness back in with their responsive settings, but that's limited. We can also add a script that will dynamically update the pixel width of the chart when the component is mounted and when the window is re-sized (it's been done before, though I'd have to dig up where I found it), but that too is a pain.~

~Height has the same problem, but I'm not as concerned about that right now.~

~[Hmm, width with highchart itself actually seems responsive: [https://jsfiddle.net/1p7s5yw6/](https://jsfiddle.net/1p7s5yw6/). I'm not sure what's going on with the react package.]~

So no idea what was going on because this wasn't working before, but I now, for the 10th time, have no width set whatsoever and the container style as `width: 100%;` and its size is adjusting just fine :P

**Comment by knod** [comment]
[Using react-jsx-highcharts]

Things that should be dug into more:
- [x] 1. Controlling number of tick marks and points on the lines better. [Discovery: if there are too many close together, it decreases the number of them automatically.]
- [x] 2. Hover/tap to see details about a point [not completely sure about tapping]
- [x] 3. Same math/resizing problem as our current version when the time interval is changed. [`endOnTick={false}`!]
- [x] 4. Dollar values
- [x] 5. Zooming
- [x] 6. Panning [can't seem to pan vertically]
- [x] 7. Layering different types of charts
- [ ] 8. Adding buttons/random elements on top of/within the area surrounding the chart

See how a lot of these details are worked out here: https://stackblitz.com/edit/base-chart-example-gxugqn

**Comment by dylanesque** [comment]
Is switching to a new chart library a certainty? If so, can we torch all/most of the old issues related to charting?

**Comment by knod** [comment]
If/when we do switch, we can torch whatever's no longer relevant 👍

**Comment by knod** [comment]
Items that are and can be done with the new Highcharts lib for the Benefits Lines graph:
- [x] Bottom/left ticks' number format (labels headers!) (https://stackoverflow.com/a/26128177/3791179)
- [x] Fixed width for ticks' text - width to not change on interval change
- [x] Thousands separator
- [x] Bottom tooltip's number format ~(maybe the same thing as ticks)~
- [x] Snippets
- [x] Button placement
- [x] Adjust button placement based on viewport width and semantic-ui-react styles (https://stackoverflow.com/a/46586783/3791179)
- [x] File name
- [x] Replace old graph
- [ ] * Test ~(@wacii or @turnerhayes , see Slack message on tech channel)~ Seems like @wacii will take a crack at solving the Highcharts testing problem.
- [x] Function descriptions
- [x] Fix 'no benefits' message so graph buttons don't overlay it
- ~Add highcharts global options to graph frosting file (change file name and maybe location).~ [1. it's going to need the `snippets` object, which is a bigger change. 2. It's got `limits` too, so is it still just 'frosting?' Also, should we move all the stuff in the src/utils/charts folder?]
- [ ] * Hover style for legend items (button-like style always, then different for active vs. inactive?)
- [ ] * Hover style for plot line. Has a mousein and mouseout hook we can use to make it bigger when hovered over.
- [ ] * Add PlotLine to Legend? Haven't found it yet and can't seem to do a vertical series. Add/remove PlotLine (can add button to legend?) - https://stackoverflow.com/a/14632292/3791179.
- [ ] * Bigger font?
- [ ] * Different zoom/pan note for touch device
- [x] * Proportional zoom
- [ ] * Vertical panning. This might help, but means chart may have set dimensions: https://api.highcharts.com/highcharts/chart.scrollablePlotArea. Not sure how it would act with zoom.

Anything with * is something that would be nice, but isn't immediately required and probably won't be done for the first PR.

Currently getting done in PR #984 as of 12/11/18.

**Comment by knod** [comment]
Looks like @wacii will cover the tests later this week, so those aren't for #984 either.

**Comment by knod** [comment]
- [ ] When zooming maxes out (based on x-axis intervals), tell the user and prevent further zooming.
