### ISSUE TITLE
Is there a way to 'redirect' before the whole VisitPage renders?

### ISSUE THREAD

**Issue by knod** [codeforboston/cliff-effects#972]
Whenever we go to the Current Benefits section or refresh the page while in the form part of the site, it looks like the `VisitPage` might be rendering and _then_ 'redirecting' and rendering the first section. Can we intercept it before the render? The 'redirect' is currently happening in `VisitPage` in `.componentDidMount()` by replacing history.

At worst, could we just do an `if` statement to prevent rendering if the history doesn't have the right section?

**Comment by turnerhayes** [comment]
Possibly in the route callback? Something like

```
<Route
                path="/visit/:clientId/:visitId/:stepKey?"
                component={ ({ match, history, ...props }) => {
                  const { clientId, visitId, stepKey } = match.params;

                  + if (stepKey !== "currentBenefits") { return (<Redirect ... />); }
                  return (
                    <VisitPage
                      { ...props }
                      history           = { history }
                      clientId          = { clientId }
                      visitId           = { visitId }
                      stepKey           = { stepKey }
                      distrustConfirmed = { distrustConfirmed || warningOff }
                      funcs             = { funcs }
                      confirmer         = { confirmer }
                      snippets          = {{ ...snippets.visitPage, langCode: snippets.langCode }}
                      clientData        = { clientData } />);
                } } />
```

Haven't tried it yet.

**Comment by turnerhayes** [comment]
Nope.

**Comment by knod** [comment]
Well, that would make it always go to the first step.

**Comment by knod** [comment]
All brainstorming is good, though 👍

**Comment by dylanesque** [comment]
.....A function to prevent that default behavior? I don't know if ```preventDefault()``` could be of help here, but maybe worth looking into

**Comment by knod** [comment]
It's not an event in the DOM like that. I think we may have it licked with a recent PR, though. I've linked that PR to this issue now. Weird that it wasn't automatically linked before.
