### ISSUE TITLE
Warn coders when they have the the wrong version of node/npm

### ISSUE THREAD

**Issue by knod** [codeforboston/cliff-effects#983]
As discussed in #979.

**Comment by turnerhayes** [comment]
When do we want to warn them?

- Pre-commit?
- Pre-lint?
- Pre-test?
- Post- or pre-install?

More? All of the above?

**Comment by turnerhayes** [comment]
FWIW, I have used [React Boilerplate](https://github.com/react-boilerplate) on other projects, and it has an analogous functionality (except it's for `npm` and not `node`--something we may want too?), and it appears it runs it pre-install (see the `npmcheckversion` script in its [package.json](https://github.com/react-boilerplate/react-boilerplate/blob/master/package.json)). Not saying this is canonical or exhaustive, just prior art to consider.

**Comment by knod** [comment]
If your versions of node/npm affect how things are installed, which I assume they do, I'd think pre-install would be ideal. I welcome other thoughts, though.

Thanks for linking to React Bolierplate. It'll make it easier for those unfamiliar (including me) to take a look to allow for a somewhat more educated discussion.

**Comment by knod** [comment]
In the PR, @turnerhayes asks:
> Another question to consider; do we want to do exact version match? Or accept higher versions/different minor/patch versions? That is, if our current node version is set to v10.13.0, should we warn if the user is on 10.13.4? 10.15.0? 12.0.0?

**Comment by knod** [comment]
Hmm, don't know enough about node/npm. I'd say just warn on a difference that has the potential to create problems, no?
